### ISSUE TITLE
TOC Layer Ordering based off LayerId not LayerOrder EMODnet Seabed Habitats live portal

### ISSUE THREAD

**Issue by GMDuncan** [jncc/web-mapper-core#110]
The "LayerOrder" field in the Layers table doesn't seem to be respected on the EMODnet Seabed Habitats live site when building the table of contents/layer list, instead, I think LayerId is being used for ordering?

Not sure if this is an fix awaiting deployment or a new issue, as I've only just "returned" to EMODnet :)

Any thoughts @andyb-esdm ?

**Comment by HelenwoodsJNCC** [comment]
I have just checked and it works fine on the MPA mapper. @andyb-esdm is it possible the fix (see #33) was only added to the MPA mapper branch of the code and not the Emodnet one?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @GMDuncan Yes. I don't think there has been a deployment to EMODnet for a very long time. @JordanPinder requested some changes to fonts etc before we could deploy but I don't think we ever did.

**Comment by GMDuncan** [comment]
Thanks @andyb-esdm
