### ISSUE TITLE
EMODnet mapper: EMODnet Human Activities layers not populating in "Add External Layers" dialogue box

### ISSUE THREAD

**Issue by GMDuncan** [jncc/web-mapper-core#127]
When selecting the "EMODnet Human Activities" option from the predefined OGC endpoints, and clicking "Get layers", the response is "No layers available from this source".

URL used is:
https://ows.emodnet-humanactivities.eu/wms

Manually adding a getCapabilities suffix and visiting the following URL _appears_ to result in a properly formed GetCapabilities response:
https://ows.emodnet-humanactivities.eu/wms?Request=GetCapabilities

EMODnet Biology URL (https://geo.vliz.be/geoserver/Dataportal/wms) is comparable in structure, and works as above with the same manual suffix. However it properly returns layers on clicking "Get Layers".
https://geo.vliz.be/geoserver/Dataportal/wms?Request=GetCapabilities

**Comment by andyb-esdm** [comment]
The method to get the external layers adds a querystring to the configured url as below:
`
const capabilitiesUrl = url + '?SERVICE=wms&REQUEST=GetCapabilities&VERSION=1.3.0';
`
I've just tested this in the browser and it returns the server capabilities in the same way as your example. I'll test by updating the url in the configuration and see if I get some layers back.

**Comment by andyb-esdm** [comment]
I'm getting a CORS error when requesting GetCapabilities from the mapper. Do you know if they have configured their geoserver (presumably) for CORS? I would have thought so otherwise most (JavaScript) mappers wouldn't work with it.

![image](https://user-images.githubusercontent.com/31621682/149118885-6d91b0a9-dc54-4df4-a21e-4a536b002f11.png)

**Comment by GMDuncan** [comment]
Ah it **is** a CORS issue! Thanks!! Apologies for some reason I didn't pick that up...

I'll let them know to fix it from their side :)

**Comment by andyb-esdm** [comment]
Great. Sometimes these things are reported as CORS errors in the browser when they're not. But since the error is explicitly stating the lack of the Access-Control-Allow-Origin header, it almost certainly is in this case.
