### ISSUE TITLE
Insertion into Umbraco as Iframe

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#13]

**Comment by SimonAnnetts** [comment]
Hi @ulric-wilson 
Here is the url that you can put in the iframe within your CMS:
http://jnccdev-map.esdm.co.uk/
or
https://jnccdev-map.esdm.co.uk/

The map is talking to a skeleton web-api at http://jnccdev-api.esdm.co.uk/ and is requesting the two items in the Map Instances box on the map. We've set the CORs policy on the web-api to allow access from any domain.
Please let me know (or send me a link to the page on your CMS) how the test goes :)

thanks

**Comment by ulric-wilson** [comment]
Simon
Mapper appears in basic fixed size iframe on page http://jncc.defra.gov.uk/default.aspx?page=7718 It seems to be rendering fine but can you test it has the functionality you expect?

thanks

Ulric Wilson
Co-Team Leader, Digital and Data Solutions
Tel: 01733 866853, Mob: 07741 901730

**Comment by andyb-esdm** [comment]
HI @LynnHeeley could you arrange to get the JavaScript to resize the iframe on window resize so we can check that the map resizes correctly too? Let me know if you need more details.

**Comment by ulric-wilson** [comment]
Added CSS to resize iframe as JS had issues I couldn’t quickly fix

Ulric Wilson
Co-Team Leader, Digital and Data Solutions
Tel: 01733 866853, Mob: 07741 901730

**Comment by andyb-esdm** [comment]
Hi @ulric-wilson 
I had read (or heard) that you couldn't use CSS to resize an iframe, which is why I suggested some js/jQuery but obviously you can - good to know this.
Thanks for doing it so quickly. It works too!

**Comment by ulric-wilson** [comment]
From here https://benmarshall.me/responsive-iframes/


Ulric Wilson
Co-Team Leader, Digital and Data Solutions
Tel: 01733 866853, Mob: 07741 901730

**Comment by SimonAnnetts** [comment]
closing this as work completed. Please open a new issue if bugs found.
