### ISSUE TITLE
Provide initial feedback on geoserver and postgres tuning as currently on staging geoserver

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#17]

**Comment by andyb-esdm** [comment]
@JordanPinder will be able to provide more information if needed.

**Comment by JamesPe** [comment]
We are still waiting for access to the file service (not everything ix exposed via the web interface).

However we have looked at the Geoserver setup.  Initial comment would be that its quite complicated - presumably with the same layer simplified to various scales to improve performance.

For static datasets like this - caching can be a major benefit.  Caching seems to have been setup for various layers but isn't showing properly in the interface, and also doesn't appear to have been enabled for integration with a  WMS request - so probably is never being used for any real world requests.  Also the current mappers return a single image (as opposed to tiles) so teh ability for any cache to be of benefit is likely to be limited.

The new mapper will use tiles - which should mean that the cache can be of real benefit.
Consider seeding the cache.
If using a cache do you need the different resolution services ?

We also suspect CORS needs to be enabled.  See https://github.com/jncc/web-mapper-core/wiki/Tips-for-installing-geoserver-on-Ubuntu-16.04.

For the Postgres server setup - harder to say as we don't have access to the server / know its specifications - or know what else its running.  We assume the normally poor default settings for Postgres have been set to appropriate figures for the server as described https://www.postgresql.org/docs/9.5/runtime-config-resource.html .

shared_buffers, work_men and maintenance_work_mem are often the places to start
