### ISSUE TITLE
Base map selection and configuration

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#18]
**Database/API:** base maps available for each map instance can be OpenStreetMaps, GoogleMaps, Bing etc. plus any base mapping configured for GeoServer.

The mapper will need to work exclusively in Web Mercator (EPSG: 3857) to support external base mapping so the GeoServer services will need to be configured for this.

**UI:** Base map selection control that is configured from the map instance configuration.

**Comment by andyb-esdm** [comment]
I've only implemented three hard-coded base layers so far: OSM, Bing and OpenTopoMap

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm just to check is there a copyright statement requirement for Bing maps?

**Comment by SimonAnnetts** [comment]
Slight changes have been made to the BaseLayers table as these are now just WMS layers.
https://github.com/jncc/web-mapper-core/wiki/Database-Schema-and-API-Endpoints

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC 
@JordanPinder
@GMDuncan
Just working on the default base layers
1. I don't think OpenTopoMap adds much and it doesn't look very good. Shall I drop it?
2. Currently we're using BingAerial - would you prefer the labelled version so you can see place names (like openstreetmap)
3. I will put the default baselayer in the config file ("Bing", "OSM" ...) but this will be overwritten if you have set a custom baselayer (e.g. an EMODnet tile WMS with visible = true in the config).

Let me know about 1 and 2.
Thanks

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm, @JordanPinder and I are both happy to drop OpenTopoMap. As for BingAerial we aren't totally. I presume the labelled version of BingAerial is just this version: https://www.bing.com/maps/aerial? I'm happy to go with the labelled version as long as it doesn't have any MPAs labelled on it like openstreetmap.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Thanks.
The labeled version includes roads too when using their api. So slightly different to your example.
I've popped it on https://jnccdev-map.esdm.co.uk/ as a test for you to look at. It's easy to revert back to Aerial only if this is too busy.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm I think i prefer without the labels as it looks a bit busy, so if we can revert that would be great.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC  I agree - I'll do that now
