### ISSUE TITLE
Map instance configuration: centre and zoom level

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#21]
Initial extent of the map instance. This could either be centre and zoom level or a predefined extent. Map extent, even when zoomed to a set extent, depends on the window aspect ratio (OpenLayers will always try to fit a zoomed to extent into the view). So probably more intuitive to go with center and zoom.

**Database/API:** appropriate columns and endpoints on the map instance configuration

**UI:** when map instance loaded, set the view centre and zoom level to configured values.

**Comment by SimonAnnetts** [comment]
centre and zoom added to MapInstance table and are provided in the information returned by the /api/MapInstance/{name} endpoint

**Comment by andyb-esdm** [comment]
implemented
