### ISSUE TITLE
Zoom to layer extent

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#23]
Control next to each layer to zoom to its extent.

The extent returned by WMS GetCapabilities isn't always ideal for zooming (but not sure if this is simply due to server-side configuration of the layer. So we could implement this as a configurable extent against the layer configuration.

Discuss with JNCC

**Database/API:** potentially have this configurable in the database and part of layer configuration OR just use GetCapabilities on the layer.

**UI:** control next to the layer to zoom to its extent.

**Comment by andyb-esdm** [comment]
Yes. Make this configurable in the database.

**Comment by SimonAnnetts** [comment]
database now has centre and zoom per layer and the api returns these. I think centre/zoom was in preference to extent as was mentioned in issue #21 so I have done it this way for consistency.

https://github.com/jncc/web-mapper-core/wiki/Database-Schema-and-API-Endpoints

**Comment by andyb-esdm** [comment]
Implemented
