### ISSUE TITLE
Restyle layers based on available GeoServer styles

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#24]
This will work from GetCapabilities that contains a styles array.

**UI:** read styles array and present dropdown of available styles next to layer. When user selects a style, the layer is re-requested with the style set in the WMS request.

Note will need to parse xml response to JSON probably (xml2json?) or can we get response back in different formats?

**Comment by andyb-esdm** [comment]
@JamesPe @SimonAnnetts 
Hit a bit of a snag with styles and layer groups.
Simon created a style 'green', which simply fills all polygons green. He had to do this as an additional style against each layer in the layer group eusm2016 (there are four of them).

I can request an individual layer in the layer group and specify the style like this: (layer: eusm2016_full, style: green)
http://jnccdev-geo.esdm.co.uk/geoserver/emodnet/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=eusm2016_full&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=green&BBOX=2504688.542848654%2C7514065.628545966%2C5009377.08569731%2C10018754.171394622

However, the mapper is requesting the 'layer' via the layergroup name: eusm2016 and it doesn't look like you can have multiple styles against a layer group. So this request (layer: eusm2016, style: green) falls back to the default style even though all the layers within the layer group individually support the green style.
http://jnccdev-geo.esdm.co.uk/geoserver/emodnet/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=eusm2016&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=green&BBOX=2504688.542848654%2C7514065.628545966%2C5009377.08569731%2C10018754.171394622

So I don't think we can support applying layer styles to layer groups and we don't 'know' what layer to specify at a particular zoom level within a group. Even if we could specify the layer (e.g. from GetCapabilities), then we'd be doing the work of GeoServer by switching to different layers at different resolutions. This sounds complex!

Suggestions?

**Comment by SimonAnnetts** [comment]
Stop using layer groups on geoserver and just use the full resolution layer, but try and enable the tile caching for the lower zoom levels? Would have to cache tiles in all available styles then too of course....

**Comment by JamesPe** [comment]
This is certainly the aim - though need to do some testing with JNCC.  Create cache at full resolution and then use a single full layer for filtered results.
Of course if there is a cached layer - the whole concept of alternative styles is a bit odd.

I think Geoserver expects you to create another GroupLayer if you want to change the style

**Comment by JamesPe** [comment]
@andyb-esdm @SimonAnnetts  -  I think this is what Geoserver expects you to do:
http://jnccdev-geo.esdm.co.uk/geoserver/emodnet/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=eusm2016_green&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=green&BBOX=2504688.542848654%2C7514065.628545966%2C5009377.08569731%2C10018754.171394622
It works - but clearly requires more config

**Comment by JamesPe** [comment]
I think we should stick with what geoserver offers - so if its a single layer WMS we can apply another offered geoserver style.
If its a layer group and another style is really wanted on it then JNCC need to create a new layer group and apply teh new style to it and add it in the mapper as a new layer

**Comment by SimonAnnetts** [comment]
@andyb-esdm So possibly then at the moment if the layerName  != legendLayerName, because layerName is actually a group then offer no alt styles. A real single layer should have layerName == legendLayerName and might then have multiple styles that can be chosen.  This sounds a bit convoluted though, and maybe we need a boolen isLayerGroup in the layer JSON instead? Or I change the styleName attribute to be a list of style names that have to be defined in the DB?

**Comment by andyb-esdm** [comment]
Hi @JordanPinder @HelenwoodsJNCC 
Can you make a decision on the necessity of this feature based on the technical limitations and sprint review dicussion?

**Comment by JordanPinder** [comment]
Hi @andyb-esdm, firstly thanks to you guys for looking into this! Helen and I are happy for this feature to be dropped - it's more of a nice-to-have, and given the complexity in implementing it it doesn't seem to be worth the effort.

**Comment by andyb-esdm** [comment]
Okay. Thanks for letting me know. It was horrible parsing the GetCapabilities xml in JavaScript anyway  :)

**Comment by andyb-esdm** [comment]
Closed - not required.
