### ISSUE TITLE
Display layer metadata provided by GeoServer

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#28]
UI: control next to layer to display layer metadata (as a popup?). This metadata comes from GeoServer GetCapabilities. May need to discuss with JNCC the role of GeoNetwork.

**Comment by andyb-esdm** [comment]
@JordanPinder to confirm that this actually just a configurable link to a separate metadata website that will open in a new tab.

**Comment by JordanPinder** [comment]
@andyb-esdm yes for EMODnet that is the case - all metadata records should point to the GeoNetwork URLs. Additionally the GeoServer layers have the metadata link pointing to GeoNetwork URL too for the link, and the GeoServer layer "abstract" is usually copy/paste directly from the GeoNetwork metadata record.

The MPA mapper seems to use a similar URL approach, but this brings up a pop-up box for a specific URL page and not GeoNetwork.

**Comment by andyb-esdm** [comment]
@JordanPinder - thanks for this.
It looks like we should be able to get the metadata url from the layer.
I guess then it's for JNCC to decide if they would prefer a popup or a new tab? The metadata can be quite long as we saw (and is already nicely formatted on the dedicated page).

**Comment by JordanPinder** [comment]
@andyb-esdm I'd be in favour of opening it in a new page as it does reduce the clutter/noise on the page, @HelenwoodsJNCC what do you think?

**Comment by HelenwoodsJNCC** [comment]
@JordanPinder @andyb-esdmIm happy enough for it to be a new tab rather than a pop-up window.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC thanks - we'll do that then.

**Comment by andyb-esdm** [comment]
Implemented

**Comment by JordanPinder** [comment]
Resolved, closing.
