### ISSUE TITLE
Switch layers off and on

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#30]
**Database/API:** layer configuration must include a 'visible' property to indicate whether the layer should be initially visible when the map instance loads.

**UI:** checkbox or switch to change layer visibility next to each layer

**Comment by andyb-esdm** [comment]
Layers can now be switched off and on (where they are displayed in the active layers control - see #31 ).
Will discuss styling at next meeting.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm The Annex A spec included the ability to toggle all layers in a group on/off simultaneously - is this something that can be easily implemented? Apologies for not flagging this earlier.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC okay - I must have missed that - sorry - a switch against each layer (and sublayer) group?

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm yes, if possible.

**Comment by andyb-esdm** [comment]
Implemented

**Comment by HelenwoodsJNCC** [comment]
When layers are switched on they are displaying in the small inset map as well as the main map - Can we turn that off.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Yes I think we can. I'll investigate.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm Currently when there are lots of layers switched on the active layers list goes off the bottom of the screen, would it be possible to be able to scroll down to see the ones at the bottom? Also, when this happens, if you drag the active layers panel the box locks to the top of the screen.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC 
1. The inset map isn't as easy to change as I'd hoped. If I understand the documentation, to do this properly, I would need to create a whole new map with just the base layer set and keep it in sync with the main map. I'll try some things with the overview map control but I'm not too optimistic - sorry.

2. Active layers list - an oversight from me here - apologies - I'll restrict the height of the container and get it to scroll.
