### ISSUE TITLE
Simple layer filter

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#34]
User should be able to run simple filters against the attributes of the WMS.

**Database/API:** layers should have configuration for filters with an attribute name matching the layer name and a data source for any list for filtering. Possibly if this data source is free text then the data source will be null. Will need some further design.

**UI:** Button to allow user to filter the layer via a dialog or have the filter setting in place next to the layer. Need to be able to clear the filter. There will be  dropdowns (or free text field) for filtering depending on configuration.

Ideally only one attribute could be filtered for each layer (much easier for UI and filter string building!). But appreciate that might not be practical. Suggest a limit of (say) 3 filterable attributes per layer.

Discuss with JNCC

**Comment by andyb-esdm** [comment]
@JordanPinder @HelenwoodsJNCC @JamesPe 

I've implemented the simple filter as a multi-select against lookup tables associated with the layer in the configuration. You can potentially have several lookups for each layer.
In the simple case with one lookup, this translates as an 'IN' query against a layer attribute. For example the screenshot would run the following filter:
select everything from the EUNIS layer where hab_type IN ('A1', 'A1.1', 'A1.11', 'A1.11+A1.16')

![image](https://user-images.githubusercontent.com/31621682/53330210-da247780-38e5-11e9-95d9-3512b765a0a3.png)

On the EMODnet mapper, there are single select, multi select and free text controls.

![image](https://user-images.githubusercontent.com/31621682/53330334-253e8a80-38e6-11e9-9ed0-99c90111352f.png)

I can implement these but, before I do, do you know why the EUNIS habitat select is single select but the OSPAR habitat one is multi select? I'm wondering why the user isn't allowed to filter by multiple habitats against EUNIS.

1. Should we allow multi selects everywhere?
2. Also, do you want a free text filter or have all filtering driven by lookup tables?

Thanks

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdmfrom an MPA mapper perspective the simple filtering could be entirely driven by lookup tables, but we would need multi selects on all the simple filters.  @JordanPinder what about for EMODnet?

**Comment by JordanPinder** [comment]
@andyb-esdm I think the current mapper only allows single select filtering on EUNIS values because it's currently done in regex - allowing multi selects in regex simply takes too long. 

Similar to the MPA mapper, multi select filtering would be needed on all the simple filters. I don't think free text filtering would be needed for EMODnet - lookups should be fine.

**Comment by andyb-esdm** [comment]
@JordanPinder @HelenwoodsJNCC 
Thanks for answering so quickly. Using CQL and the IN expression makes it very straightforward to do multi selects so we might as well have them everywhere. I'll polish it up a bit and release it to the test environment today.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm @JordanPinder I found a bit of a bug today. If you activate a filter on a layer, then turn the layer off and back on again. The filter is remembered on layer data but it isn't indicated with the filtered icon and the ticked boxes are cleared on the filter pop-up tool. We would like to retain the fitlered status but it is important that the filter tool and indicator retain the info as well.

**Comment by JamesPe** [comment]
Thanks Helen, Andy has the day off today - but is in again tomorrow.  That doesn't sound too complicated a bug to fix

**Comment by JordanPinder** [comment]
@andyb-esdm @JamesPe let me know when this can be closed, or feel free to close when it's implemented.

**Comment by andyb-esdm** [comment]
@JordanPinder @HelenwoodsJNCC 
Haven't fixed the bug yet so keep this open.

**Comment by andyb-esdm** [comment]
Now fixed.
