### ISSUE TITLE
Flag filtered layers

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#35]
Layers that have been filtered should be flagged in the UI to indicate this. User should be able to remove the filter.

**UI:** icon to indicate a filtered layer that can be clickable to display the filter and clear it?

**Comment by andyb-esdm** [comment]
It sort of does this at the moment but will keep issue open until simple filters issue completed!

**Comment by andyb-esdm** [comment]
Implemented by highlighting filter icon red.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm Can the tooltip be changed if a filter is active to say something like 'layer currently filtered'?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Yes. That's no problem.

**Comment by andyb-esdm** [comment]
Implemented
