### ISSUE TITLE
Create filter lookup tables and endpoints

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#36]
Database/API: need to create filter lookups that can be associated with layer filtering configuration.

JNCC to assist with population of lookups.

**Comment by SimonAnnetts** [comment]
table called Lookup exists and has API endpoint /api/Lookup/{category}
See documentation at https://github.com/jncc/web-mapper-core/wiki/Database-Schema-and-API-Endpoints

**Comment by SimonAnnetts** [comment]
closing this as work completed. Please open a new issue if bugs found.
