### ISSUE TITLE
Gazetteer

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#39]
Database/API: api endpoint for gazetteer requests based on partial match of user entered string.
JNCC will provide gazetteer data.

UI: autocomplete wired up to the api endpoint and on item select zoom to returned lat/long.

**Comment by andyb-esdm** [comment]
The gazetteer table will be in the mapper database.
JNCC will be able to provide the gazetteer data.

**Comment by LynnHeeley** [comment]
Andy can you remind us of the data /fields that are needed for this. Jordan will get to it early next week.

**Comment by andyb-esdm** [comment]
@LynnHeeley 
@SimonAnnetts will provide you with required schema.
Do you need any other data sources for the gazetteer (e.g. public APIs like geonames)? Or is this likely to be irrelevant since they only cover terrestrial areas.

**Comment by andyb-esdm** [comment]
@JordanPinder 
Columns required: name, longitude (x), latitude (y), zoom

**Comment by SimonAnnetts** [comment]
@JordanPinder 
I will create the table using Entity Framework Migrations via the web-api today

**Comment by SimonAnnetts** [comment]
table 'Gazetteer' now created in the same database as the rest of the web-api tables.

Schema updated in documentation:
https://github.com/jncc/web-mapper-core/wiki/Database-Schema-and-API-Endpoints

**Comment by SimonAnnetts** [comment]
API documentation updated in
https://github.com/jncc/web-mapper-core/wiki/Database-Schema-and-API-Endpoints

**Comment by SimonAnnetts** [comment]
@andyb-esdm will you need to specify a limit on the number of results to return?

**Comment by JordanPinder** [comment]
@SimonAnnetts thanks for this Simon! Useful for me to see the configuration, should have the EMODnet gazetteer finished soon.

**Comment by JordanPinder** [comment]
@SimonAnnetts just been looking at this a little more - if I'm correct OpenLayers has zoom to extent functionality which only requires the bounding box coordinates of an area, and I _think_ this also selects a zoom scale depending on the screen. Not sure if that'd be feasible to implement?

**Comment by andyb-esdm** [comment]
@JordanPinder Yes you can do map.getView().fit(myExtent);

**Comment by JordanPinder** [comment]
@andyb-esdm grand, so would that eliminate the need for a zoom level per the database schema?

**Comment by andyb-esdm** [comment]
@JordanPinder Presumably you want to put an extent into the database schema instead e.g. minx, miny, maxx, maxy. Or just have the map zoom to a point? A point doesn't have an extent so we would need a default zoom level. Sorry if I misunderstand.

**Comment by JordanPinder** [comment]
@andyb-esdm Sorry for not clarifying properly! Yes, openlayers would use the min max x y and zoom to the extent, which I imagine would be ideal as it reduces the need for a zoom scale, but that would mean altering the schema to include the extent columns. Alternatively we could also use the current approach zooming to a point and setting the zoom scale. Either approach is fine with me as I have the parameters already, just thought I'd get your opinions :)

**Comment by andyb-esdm** [comment]
> @andyb-esdm will you need to specify a limit on the number of results to return?

Sorry I didn't answer this, Simon. What did you do for squirrels? That worked well.

**Comment by andyb-esdm** [comment]
@JordanPinder well we can do either with equal effort. Let Simon know what you would like and I'll ensure the map behaves appropriately. Thanks very much.

**Comment by JordanPinder** [comment]
@SimonAnnetts any thoughts on this?

**Comment by andyb-esdm** [comment]
I imagine some of the gazetteer entries will be regions (e.g. celtic sea) so an extent would make more sense.
If you do switch to extent, please provide separate fields.

**Comment by SimonAnnetts** [comment]
Yes, you will always get them as separate fields in the JSON (as you do the map centres now), but in the DB it might be easier to manage them as one field containing an extent '[minX, minY, MaxX, maxY]' which I parse for you into separate values.
This is how the LayerCentre and MapCentre work now..

But I need a decision.... is it zoom or extent??? :)

**Comment by JordanPinder** [comment]
As Andy mentioned the entries will mainly be regions, so probably better to go with extent. Will get you the sample sent across now.

**Comment by SimonAnnetts** [comment]
API documentation updated in
https://github.com/jncc/web-mapper-core/wiki/Database-Schema-and-API-Endpoints

The gazetteer data from the spreadsheet is also loaded into the DB.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm @SimonAnnetts a few comments from the UAT regarding this issue:
- Can we implement partial string matching - this would be particularly useful if the groupings are shown e.g. so you could type exclusive and bring up all the exclusive economic zone matches. 

- I think we need to update the default description in the box, at the minute users think it looks like a total free text option where you can type anything and it will go there. Maybe something more specific like search marine regions or start typing to see options @JordanPinder what do you think?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @JordanPinder 

Agree on point one.

For point two, we could house the search box in a container with some explanatory text and a title. But I quite like the minimal effect. So instead I can change the placeholder text. Please let me know what you would like.

**Comment by SimonAnnetts** [comment]
@HelenwoodsJNCC @JordanPinder @andyb-esdm 
If we are going to make the gazetteer return results for everything that contains the search string rather than everything that starts with the search string, should we limit the results, or only start searching after say 3 letters have been typed in the search box. Other wise just typing the letter E for example would likely return nearly everything in the gazetteer!

**Comment by HelenwoodsJNCC** [comment]
@SimonAnnetts asking users to type three letters sounds reasonable enough to me.

**Comment by SimonAnnetts** [comment]
If @JordanPinder is in agreement too then @andyb-esdm shall I implement that server side? Only return results if the query string is 3 characters or greater? That will provide a level of protection for performing lookups on the database if it's enforced in the web-api.

**Comment by JordanPinder** [comment]
@SimonAnnetts @andyb-esdm yes please, limiting to 3 characters is fine with me!

**Comment by SimonAnnetts** [comment]
Just pushed that change to jnccdev-map.esdm.co.uk -please test and if happy then I can push to your staging server also.

**Comment by SimonAnnetts** [comment]
I've spotted a bug already..... having nothing in the box returns everything! This is due to there being an endpoint called /api/gazetteer/ .  I will remove this endpoint!

**Comment by SimonAnnetts** [comment]
ok bug fixed.

**Comment by andyb-esdm** [comment]
Autocomplete has a few UX considerations.

For example, we found that the minimum 3 letter search term has been difficult for users in other projects (e.g. CMSi) because a lot of people speculatively search to see what's available. Your chances of getting hits when you don't know what's there are a lot lower if you have a minimum length.

A lot of people wanted to see what begins with a certain letter. Also results are often prioritised by matches that start with the search term (implemented like this  in SQL https://stackoverflow.com/a/6265609/87609 if it can be translated easily to LINQ).

Limiting results to a reasonable number is one way around the 'select everything that contains e' problem.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm I see what you mean if people don't know what they can search for. So you are suggesting we should go for no minimum search length, prioritise those that start with the search string, and limit the results. Could return say top 10 matches?

**Comment by SimonAnnetts** [comment]
OK, can we open this question up again to see if this has changed the requirement on the gazetteer? I'm happy to try and implement whatever is specified.
@andyb-esdm so you are suggesting - 
- no minimum length of search term
- limit number of results
- order by the 'startswith' result matches first, then the 'contains' results matches afterwards
?
@HelenwoodsJNCC @JordanPinder 
any comments please? The previous solution (min 3 characters and a 'contains' type search) can be tried on our dev server. Your server still has the original 'startswith' search. Andy is suggesting another possible solution.

**Comment by andyb-esdm** [comment]
Something like that would be a better experience I think. There's already some client side control e.g. a small delay to the request (250ms) so that someone typing in more than one character won't generate multiple requests to the api. Also, it will only generate requests when the search term has changed client-side.

**Comment by HelenwoodsJNCC** [comment]
I am happy to go with Andys experience on this, and just limit the number of results returned. @JordanPinder do you have a strong preference?

**Comment by SimonAnnetts** [comment]
@andyb-esdm 
Something like this in LINQ seems to work:
~~~
            gazetteer = await _context.Gazetteer
                .Where(g => g.Name.ToUpper().Contains(name.ToUpper()))
                .OrderBy(g => g.Name.ToUpper().IndexOf(name.ToUpper()))
                .ToListAsync();
~~~
but still testing it....
@HelenwoodsJNCC @JordanPinder
If we limit the results, do we pick a value here and now and hard code it or should it be configurable somewhere - either in the web-api config file, or in the database, say in mapInstance ?

**Comment by andyb-esdm** [comment]
@SimonAnnetts The constraint here is how many to display in the drop down let's say 20!

**Comment by JordanPinder** [comment]
@SimonAnnetts @andyb-esdm 20 sounds like an appropriate amount, but having it configurable would be great - ideally in the database itself if that's possible?

**Comment by andyb-esdm** [comment]
Made the placeholder text more clear. It now says 'Search for marine regions ....'

**Comment by SimonAnnetts** [comment]
Gazetteer record limit is configurable in the appsettings.json
in the subsection:
~~~
    "WebApiConfig": {
      "TestDataWMSUrl": "//staging.ows.emodnet-seabedhabitats.eu/emodnet/wms",
      "MaxGazetteerResults": 30
    }
~~~
