### ISSUE TITLE
Create configuration schema and API endpoints for mapper

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#40]
Proposed structure is hierarchical. Broadly:
MapInstance -> LayerGroups -> Layers -> Filters

Various LUT endpoints
and API to reflect this

MapInstance will include descriptive html, baselayers and a collection of layers
LayerGroups will have a configurable name (sortorder?)
Layers will have the url, display on/off by default, opacity etc.
Filters will be key value pairs between the layer attribute to be filtered and the lookup/endpoint for the dropdown.

This issue does **not** include any schema for map permalinks since this needs to be finalised.

**Comment by SimonAnnetts** [comment]
I have defined a preliminary schema and have created various API endpoints to expose the (test) data in the database.
I have documented it as best as I can here:
https://github.com/jncc/web-mapper-core/wiki/Database-Schema-and-API-Endpoints
and would appreciate any/all comments!

**Comment by SimonAnnetts** [comment]
closing this as work completed. Please open a new issue if changes are required to the schema as it stands now.
