### ISSUE TITLE
AWS VM for EMODnet mapper website and API

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/web-mapper-core#41]
Requirement for AWS VM to host both the mapping website (that will be embedded into Umbraco iframe) and the webAPI site that will be used by mapper/filters.
- base VM on t3.micro instance (1GB ram, 2 vCPU)
- tag VM with Emodnet project tag (should already exist)
- ensure ESDM have access (James, Andy, Simon) as well as JNCC Devs

**Comment by SimonAnnetts** [comment]
We will need SSH access to this from 5.196.45.195 (our staging server) to a local unprivileged user account (I have assumed for the rest of this document that the user is called 'esdm' as it is on our server, but let me know if different). We will need you to add this public key to ~/.ssh/authorized_keys so we can login using public/private key pair.:
~~~~
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHLOO+/9mQCUTZj7ehBu/R+PxS8otLNyAP1GTDH70+qxGBEVpmmGTpV1qYhtt/1U+EseaHICPZJQ8EB5MQYskxYZV0/KP+ZG/JUubcjiVPkyyiZoZvhU14b5nmoYVJR0JOaj3t7iJO5egBzGJuHNgUCOhqv7bWbW6bwRkKe7LWtOIfHZgVnktQwhGqE4HrSgzNgESd/I9Bgi022pH2tzsw/8+5/mEq8+rvYggIMFl50WJ3RgOn12sdy/QC94t0QddBLq53nUjXcEIuoRR39QjT9bN5OIqtxYXLjh1I6twloGdmAz2BctirKiIOsqeYdH8K69DeZG2Xx1M1zNuDIXfF esdm@esdm-xen1-04
~~~~
We will be connecting using SFTP or SSHFS to upload files to this user account, both for the web-api application and the static HTML files for the web-map application but we will also need a bash prompt via SSH.

Apache needs to be configured some thing like this (this is from our staging server)... you will need to change domain names and home directory names to match. We have used separate sub-domains for the web-api and the web-map as apache needs to serve them differently.
In /etc/apache2/sites-available/001-webapi.conf
~~~~

<VirtualHost jnccdev-api.esdm.co.uk:80>
        ServerName jnccdev-api.esdm.co.uk
        ServerAdmin simonannetts@esdm.co.uk
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:5000/
        ProxyPassReverse / http://127.0.0.1:5000/
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>

<VirtualHost jnccdev-map.esdm.co.uk:80>
        ServerName jnccdev-map.esdm.co.uk
        ServerAdmin simonannetts@esdm.co.uk
        DocumentRoot /home/esdm/web-published/jncc-web-map
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        <Directory /home/esdm/web-published/jncc-web-map>
          Require all granted
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
        </Directory>
</VirtualHost>
~~~~
Once this is configured and apache is running you can install and run letsencrypt to create the https configs automatically, or install your own wildcard cert and configure. We used letsencrypt like this:
~~~~
certbot --apache -d jnccdev-api.esdm.co.uk -d jnccdev-map.esdm.co.uk
~~~~
and it created a lovely SSL config for us (and certificates) like this in /etc/apache2/sites-available/001-webapi-le.conf:
~~~~
<IfModule mod_ssl.c>
<VirtualHost jnccdev-api.esdm.co.uk:443>
        ServerName jnccdev-api.esdm.co.uk
        ServerAdmin simonannetts@esdm.co.uk
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:5002/
        ProxyPassReverse / http://127.0.0.1:5002/
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/jnccdev-api.esdm.co.uk/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/jnccdev-api.esdm.co.uk/privkey.pem
</VirtualHost>
</IfModule>

<IfModule mod_ssl.c>
<VirtualHost jnccdev-map.esdm.co.uk:443>
        ServerName jnccdev-map.esdm.co.uk
        ServerAdmin simonannetts@esdm.co.uk
        DocumentRoot /home/esdm/web-published/jncc-web-map
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        <Directory /home/esdm/web-published/jncc-web-map>
          Require all granted
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
        </Directory>
        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/jnccdev-api.esdm.co.uk/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/jnccdev-api.esdm.co.uk/privkey.pem
</VirtualHost>
</IfModule>
~~~~

We will also need a systemd service file to start the dotnet application. Something like this in /etc/systemd/system/jncc-web-api.service :
~~~~
[Unit]
Description=JNCC .NET Web Mapper API

[Service]
WorkingDirectory=/home/esdm/dotnet-published/jncc-web-api
ExecStart=/usr/bin/dotnet /home/esdm/dotnet-published/jncc-web-api/jncc-web-api.dll
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=jncc-web-api
User=esdm
Group=esdm
Environment=ASPNETCORE_ENVIRONMENT=Production
Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false

[Install]
WantedBy=multi-user.target
~~~~

Don't enable it yet as we need to upload some files to make it work, but when you do:
~~~~
systemctl daemon-reload
systemctl enable jncc-web-api
systemctl start jncc-web-api
~~~~

When we upload a new version of the service we will issue a 'pkill dotnet' command (as user esdm from the bash prompt) and systemd should relaunch the process again with the new code.

Please let me know if I've forgotten anything!

**Comment by paul-gilbertson** [comment]
Can you see if you can login to ec2-63-34-227-23.eu-west-1.compute.amazonaws.com ?

**Comment by SimonAnnetts** [comment]
Yes I can login using SSH. Thanks!
I thought the server would be Ubuntu 16.04, but it seems to be 18.04. This is probably not an issue as long as we can still have dotnet-sdk and apache installed.

**Comment by paul-gilbertson** [comment]
Apache set up with the virtual hosts, api.emodnet-seabedhabitats.eu and prelive.mapper.emodnet-seabedhabitats.eu. Prelive will be dropped when we switch mapper.

SSL certificates being sorted.

**Comment by paul-gilbertson** [comment]
OK, dotnet-sdk-2.2 and apache2 are both configured. I will do the systemd when the app is on there, and sort SSL when it arrives.

63.33.194.195 should also be accessible and api.mpa.jncc.gov.uk and mapper.mpa.jncc.gov.uk will be pointing there soon.

**Comment by paul-gilbertson** [comment]
Closing ticket, remaining steps dissolved to new tickets

**Comment by SimonAnnetts** [comment]
If I go to ec2-63-34-227-23.eu-west-1.compute.amazonaws.com I get the default ubuntu webpage.
63.33.194.195 is not accessible directly (a good thing :)
api.mpa.jncc.gov.uk and mapper.mpa.jncc.gov.uk still have no DNS so cannot test if the VirtualHost containers in the apache config are working.

**Comment by paul-gilbertson** [comment]
which protocols for mod_proxy do you need?

**Comment by SimonAnnetts** [comment]
Apache only needs to talk to the dotnet application over HTTP at 127.0.0.1:5000
To then outside world apache can serve this proxied application via HTTP or HTTPs

I noticed that in my example configs above, the virtual host container for the proxy on port 443 is proxying to the wrong port (says 127.0.0.1:5002) should be 127.0.0.1:5000. I forgot to edit that one in the example.

**Comment by paul-gilbertson** [comment]
OK, have loaded mod_proxy and mod_proxy_http.

**Comment by SimonAnnetts** [comment]
thanks.
Trying to access http://api.mpa.jncc.gov.uk
just hangs. It should proxy through to the jncc-web-api application running on localhost:5000

I have an instance of the web-api running currently.

Do the virtual host containers that do the reverse proxies have the right server name 'api.mpa.jncc.gov.uk' in them and is there any firewall blocking access perhaps?

**Comment by paul-gilbertson** [comment]
I think you are on the EMODnet box, not MPA... so it is http://api.emodnet-seabedhabitats.eu/  That said, not sure it is working properly. Looking deeper into the Proxy config...

**Comment by paul-gilbertson** [comment]
Works now. For future reference, VirtualHost needs to map to *:80 and difference on ServerName

**Comment by SimonAnnetts** [comment]
Ok, that works now on http://api.emodnet-seabedhabitats.eu/
but not on 
https://api.emodnet-seabedhabitats.eu/
So should the map part of the application go onto 
http://map.emodnet-seabedhabitats.eu/ ?? 
We can't use http://mapper.emodnet-seabedhabitats.eu/ as that points to the existing map site.

**Comment by paul-gilbertson** [comment]
As per above: Apache set up with the virtual hosts, api.emodnet-seabedhabitats.eu and prelive.mapper.emodnet-seabedhabitats.eu. Prelive will be dropped when we switch mapper.

**Comment by SimonAnnetts** [comment]
ok
prelive.mapper.emodnet-seabedhabitats.eu
works too and goes to my test Hello World page, but still no https on either site.

**Comment by paul-gilbertson** [comment]
Working on the SSL certificates

**Comment by paul-gilbertson** [comment]
See #47
