### ISSUE TITLE
Create AWS VM for MPA mapper website and API

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/web-mapper-core#42]
Requirement for AWS VM to host both the mapping website (that will be embedded into Umbraco iframe) and the webAPI site that will be used by mapper/filters.

- base VM on t3.micro instance (1GB ram, 2 vCPU)
- tag VM with MPAmapper project tag (should already exist)
- ensure ESDM have access (James, Andy, Simon) as well as JNCC Devs

**Comment by paul-gilbertson** [comment]
63.33.194.195 should also be accessible and api.mpa.jncc.gov.uk and mapper.mpa.jncc.gov.uk will be pointing there soon.
