### ISSUE TITLE
Finalise specification for adding external layers

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#45]
Linked to #32

**Comment by andyb-esdm** [comment]
I guess we're likely to copy the way this is done on EMODnet here?

**Comment by SimonAnnetts** [comment]
Hi @JordanPinder @HelenwoodsJNCC 
When adding external WMS layers, do you want to be able to pre-define some of these layers like you do on the existing mapper by having a database table read by the web-api to provide a selectable list, as well as the text box for an external WMS URL?
If so, should the list of external WMS layers be defined per map instance, or just be a global list that is available to all map instances?

**Comment by HelenwoodsJNCC** [comment]
@SimonAnnetts Yes we would like to be able to pre-define some of the layers, preferably per map instance. For the MPA mapper we will likely have the EMODnet WMS listed but this is obviously redundant in it's own instance.

**Comment by SimonAnnetts** [comment]
Thanks @HelenwoodsJNCC.
@andyb-esdm - 
I wonder if we could just leverage the existing layers table and add a field IsExternal to signify that the layer does not usually appear in the ALL LAYERS list and that the WMS url and name etc are just shown in a popup list when the user clicks on the 'Add external WMS layer' link? (along with the text box for users to add their own WMS url)
Of course these 'external' layers could then be added to the 'ALL LAYERS' list under the layer group that the 'external' layer has been defined under if chosen by the user.

**Comment by andyb-esdm** [comment]
Yes, that would work. Makes me wonder though, why have them displayed separately. You could have just an 'external layers' layer group in the ALL LAYERS list from the outset with these listed inside. Then, if the user adds any custom external layers, they could be added to this group.

**Comment by SimonAnnetts** [comment]
True..... I was just following the way that the existing mapper does it, but you are right, it could just be another LayerGroup sorted by Order to be last. Where would you put the Add External WMS link and it's text box though? A link within the Layer Group area and a UI popup for input? Once the external WMS is input a further choice of layers returned from the getcapabilities would need to be displayed, allowing the user to pick one or more layers to add.

**Comment by andyb-esdm** [comment]
Okay. That sounds like an idea.
@HelenwoodsJNCC @JordanPinder 
We're suggesting that pre-configured external layers are presented in a 'special' layer group on the mapper (calll external layers or similar) and a control on that group to add custom external layers (you get a popup similar to current EMODnet).
@SimonAnnetts if we did this we would need to identify the layergroup as an external layer group with a property on the group.
What functionality should external layers support? i.e. GetFeatureInfo, Opacity etc.

**Comment by SimonAnnetts** [comment]
@andyb-esdm 
So yes, I would add a field to the LayerGroup table - 'IsExternal'. This tells you that this is the LayerGroup that externally supplied WMS layers should go, and that it needs to provide the link/button for users to select external layers. Pre-defined external layers (received via the web-api) are just child layers of this layer group, but are only visible if added from a list.
I think the external layers should support GetFeatureInfo, and possibly getLegendImage. Wouldn't opacity control come out of the box in the interface anyway? The pre-defined external layers can of course specify it as it is a layer parameter, but external layers from WMS url should probably just default to 0.8.

**Comment by SimonAnnetts** [comment]
Having looked aat it a bit more.... the current mapper does not list external layers individually though, only external WMS sources and it queries for layers, so maybe we do need another table for WMS sources rather than specify external layers individually in the layers table?

**Comment by andyb-esdm** [comment]
Okay. Sounds like another table would be neater.

**Comment by JordanPinder** [comment]
@andyb-esdm @SimonAnnetts yes, current mapper just sources the WMS and then lists all individual layers within the WMS. I think this approach is still required, but the ability to list pre-defined layers is also needed - by pre-defined this is referring to listing a specific layer from a WMS source, from an EMODnet perspective this would be used for the main data products from each EMODnet portal (e.g. a Bathymetry layer, a Geology layer etc.). 

Hope this makes sense, @HelenwoodsJNCC what do you think?

**Comment by andyb-esdm** [comment]
@JordanPinder whenever you ask a client this or this? The always answer why not both ;) No problem. Thanks.

**Comment by HelenwoodsJNCC** [comment]
@JordanPinder @SimonAnnetts @andyb-esdm MPA mapper works much the same way as Jordan describes above, so the approach makes sense to me.

**Comment by SimonAnnetts** [comment]
So if I read this right, we need an extra table to hold WMS sources - this table is a child of MapInstance so that these external sources can be different per map instance. The mapper will do a getCapabilities request of the user's chosen WMS source and show the user the list of all the layers that will get added to the mapper. (Same functionality as existing mapper). The user cannot choose which layers, they will all get added to the ALL LAYERS ui element under the LayerGroup that has the proposed field 'IsExternal' set to true.
This LayerGroup will have a name of 'External Layers' or something like that (configurable). 
We also need to still be able to populate the Layers table with external layers and these layers will need to belong to the above LayerGroup so we know they are external layers.
The UI (a modal popup?) will need to show both the pre-defined WMS sources and the pre-defined External (single) Layers, as well as provide a text box for the user to input their own WMS url.

@JordanPinder @HelenwoodsJNCC @andyb-esdm if you are all happy with this 'specification', I will make the required changes to the web-api and database schema to enable this.

**Comment by HelenwoodsJNCC** [comment]
@SimonAnnetts yes I am happy with that.

**Comment by JordanPinder** [comment]
@SimonAnnetts as am I :)

**Comment by SimonAnnetts** [comment]
Changes made to our test server database, web-api updated and documentation updated at https://github.com/jncc/web-mapper-core/wiki/Database-Schema-and-API-Endpoints

**Comment by andyb-esdm** [comment]
@SimonAnnetts @JordanPinder @HelenwoodsJNCC @JamesPe 
Hit a bit of a snag with external layers over the weekend - CORS. The example external server does not have CORS set up and so the mapper can't access the wms service. I think this is going to be an issue for many external services. So maybe we need a proxy controller on the api that we can route requests for external services?

![image](https://user-images.githubusercontent.com/31621682/54113076-6f903300-43df-11e9-97b2-70e650e50e38.png)

**Comment by SimonAnnetts** [comment]
Seems to be working for me? (on this particular layer anyway)
![Screenshot_2019-03-12_08-38-10](https://user-images.githubusercontent.com/725219/54185985-37055d80-44a2-11e9-8030-efc5e6f432ee.png)

**Comment by andyb-esdm** [comment]
@SimonAnnetts How strange - it works from localhost for me this morning too. No amount of 'empty cache and hard reload' would fix it on Sunday. I'll test with the other external data sources today.

**Comment by JordanPinder** [comment]
@andyb-esdm @SimonAnnetts this is hopefully a simple one to amend - is it possible to get the "Add external layer" link included under the "External Layers" group? Currently it seems to be a little confusing for people when they're adding layers, viewing etc.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm @SimonAnnetts I presume we can't get legend and feature info from the external sources? Users find this a bit confusing so if we can't might be better to disable these options for external layers.
