### ISSUE TITLE
Database requirement for web-api

### ISSUE THREAD

**Issue by SimonAnnetts** [jncc/web-mapper-core#46]
We need a separate database on the server running the emodnet_staging database initially.

If possible:
Database name JNCCWebApi
Owner: jncc-web-api (for creating tables/indexes etc)
Read user: jncc-web-api-read (for select priv only on all tables in db)
Write User: jncc-web-api-write (select/update/insert/delete privs on all tables in db)

sorry if I've assigned this to the wrong person!

**Comment by SimonAnnetts** [comment]
can you confirm that the host I need to point the api at is:
jncc-spatial.c9k3pg5plo3u.eu-west-1.rds.amazonaws.com 
and also can you create the database 'emodnet_web_api'  for me please if it's not already there and make sure that I can see it with the 'esdm_emodnet_read_user' which you previously set up for us?
At the moment I have no access with the 3 new users that have been created, but this is probably for the best that they only connect from the web-api-mapper servers.

**Comment by paul-gilbertson** [comment]
DB server is correct. Your esdm_emodnet_read_user account has read-only access to emodnet_web_api now. emodnet_web_api has read-write access.

**Comment by paul-gilbertson** [comment]
Firewall rules altered to allow API/Mapper servers to connect

**Comment by SimonAnnetts** [comment]
Hi @paul-gilbertson 
I still cannot see the emodnet_web_api schema when logged in as esdm_emodnet_read_user :(

Also the web-api application can now connect to the postgres instance but I'm getting this error:
'PostgresException: 28000: no pg_hba.conf entry for host "63.34.227.23", user "emodnet-web-api", database "emodnet_web_api", SSL off'

**Comment by paul-gilbertson** [comment]
Can you use SSL? It is required by standard.

**Comment by SimonAnnetts** [comment]
Let me check the config. It might need a certificate or a CA if your postgres is using self signed.

I'll get back to you - probably tomorrow now

**Comment by SimonAnnetts** [comment]
Ok, SSL is set but now getting:

28P01: password authentication failed for user "emodnet-web-api"
I'm using the password Lynn sent me.

**Comment by paul-gilbertson** [comment]
Try now... is working for me.

**Comment by SimonAnnetts** [comment]
I'm still having problems. I would like to eliminate if it is an issue with dotnet and the characters used in the password. Can you
apt install postgresql-client-common
for me please so I can try and login via the command line postgresql client 'psql' ?
thanks

**Comment by paul-gilbertson** [comment]
Done

**Comment by paul-gilbertson** [comment]
psql -h jncc-spatial.c9k3pg5plo3u.eu-west-1.rds.amazonaws.com -U emodnet_web_api "sslmode=require"
with the current password works from that box. Do you need a less 'symbol filled' password set?

**Comment by SimonAnnetts** [comment]
I've just figured out what I'm doing wrong!
Duh....
Sorry for wasting your time... I had the username wrong.
I've got another issue now from dotnet entity framework migration not being able to create the database tables, but I need to investigate that further.

**Comment by SimonAnnetts** [comment]
ok this one is:
Npgsql.PostgresException: 3F000: no schema has been selected to create in
So I check what schemas are visible and which are searched for:

~~~~
select schema_name from information_schema.schemata;
    schema_name
--------------------
 pg_catalog
 information_schema
(2 rows)
~~~~
When you create a new table, it will need to be placed under one of these schemas. So if we have a create table posts (...), how does postgres know what schema to put it under?

Postgres checks your search_path for a default.
~~~~
show search_path;
   search_path
-----------------
 "$user", public
(1 row)
~~~~
I think the user needs the USAGE privilege on the 'public' schema as the user can't see that:
~~~~
grant usage on schema public to public;
~~~~
and possibly:
~~~~
grant create on schema public to public;
~~~~

**Comment by paul-gilbertson** [comment]
You are right, missing permission. Fixed.

**Comment by SimonAnnetts** [comment]
Yep, can see the public schema now:
~~~~
select schema_name from information_schema.schemata;
    schema_name
--------------------
 pg_catalog
 information_schema
 public
(3 rows)
~~~~
The dotnet application now starts correctly and creates the tables that it needs.

**Comment by SimonAnnetts** [comment]
Hi
The web-api on ec2-63-34-227-23.eu-west-1.compute.amazonaws.com can no longer talk to the database server on jncc-spatial.c9k3pg5plo3u.eu-west-1.rds.amazonaws.com. The connection times out. This is the same with the psql command line client too.

**Comment by mattdebont** [comment]
Hi Simon could you check again for me, think I have it sorted, its was a DNS resolution problem as before it was resolving externally now it should be resolving internally

**Comment by SimonAnnetts** [comment]
Yes, that is working now. Thank you!
