### ISSUE TITLE
SSL Certificates for Mappers and APIs

### ISSUE THREAD

**Issue by paul-gilbertson** [jncc/web-mapper-core#47]
Add SSL certs to the two VMs Apache installs.

**Comment by SimonAnnetts** [comment]
I still cannot connect to https://prelive.mapper.emodnet-seabedhabitats.eu/
http://prelive.mapper.emodnet-seabedhabitats.eu/ works.
Is there a firewall on port 443 ?

**Comment by JordanPinder** [comment]
@LynnHeeley @paul-gilbertson same for this issue - I also get the same problem @SimonAnnetts mentioned.

**Comment by paul-gilbertson** [comment]
Both api and prelive have SSL. Prelive is using 'letsencrypt' free 90 day cert.

**Comment by SimonAnnetts** [comment]
This is now working. Thanks.

**Comment by paul-gilbertson** [comment]
MPA certs also done
