### ISSUE TITLE
Provide file access to JNCCs staging geoserver

### ISSUE THREAD

**Issue by JamesPe** [jncc/web-mapper-core#49]
This was raised on 23/01 via email - but I think may have been forgotten.

Simon suggested - "The best way to get file access to their staging server is for them to allow SSH access from our dev server to theirs. I can then setup a SSHFS link to their server and make part of their file tree mounted into part of ours (which can then be shared via samba). "

"There quite a lot of things that require access to the files themselves – not everything is exposed through the web interface.
I’d like to have a look and see how your cache is building – I have my suspicions that’s not really doing very much at the moment.

Also moving forwards all the templates for getFeatureInfo requests (assuming we are going to help you with any sort of customisation for this) are driven by editing small files in the relevant folder.
On our geoserver I have a samba share onto the root of geoserver
Is it possible to have something similar on your staging version ?  Otherwise I guess we can try and do it on our copy and just send you the files each time – but I can see that getting tedious"

**Comment by paul-gilbertson** [comment]
Same SSH key as API?

**Comment by JamesPe** [comment]
I guess so - but Simons not in till tomorrow to check with

**Comment by SimonAnnetts** [comment]
Yes.... same SSH key.

**Comment by paul-gilbertson** [comment]
Done, same user and key. Ping this ticket if you need any elevated privs.

**Comment by SimonAnnetts** [comment]
ssh esdm@jncc-spatial.c9k3pg5plo3u.eu-west-1.rds.amazonaws.com

just hangs. Is there a firewall preventing TCP port 22 access from 5.196.45.195 ?

**Comment by JordanPinder** [comment]
@LynnHeeley @paul-gilbertson when possible can someone look into this please? It was flagged earlier in the project management meeting

**Comment by paul-gilbertson** [comment]
Geoserver is on ec2-34-243-56-82.eu-west-1.compute.amazonaws.com

**Comment by SimonAnnetts** [comment]
ok thanks Paul.
I realised my mistake and just logged in just now with
ssh staging.ows.emodnet-seabedhabitats.eu

So we need write access to the /data/geoserver/workspace/emodnet directory, but these are all owned by tomcat:tomcat. Would adding esdm to the tomcat group be enough?

**Comment by paul-gilbertson** [comment]
Added, and added group write permission to those files.

**Comment by SimonAnnetts** [comment]
This is now working, although of course any files or directories we create in the filesystem there will be owned by esdm:esdm, but they will have the permissons 0775/0664 so should be visisble to tomcat user running geoserver.
