### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#5]

**Comment by JamesPe** [comment]
Some existing functionality requires the provision of a filter on the URL e.g. https://www.emodnet-seabedhabitats.eu/access-data/launch-map-viewer/?mapInstance=MESHAtlanticMap&mapZoomToId=GB001532&mapZoomToField=GUI&mapZoomToLayer=AllMappingAreas,MESHSurveysPoly,UnprocessedImageAreas .  Whilst agreed its not in the spec if it fell out of the Permalink work that would be useful.  Current thinking with the advanced filtering being a paramterised geoserver view is making us think that url permalinks maybe possible
