### ISSUE TITLE
Implement graceful error handling if mapinstance doesn't exist (any API endpoint)

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#50]
Currently there's no error handling implemented for non-existent api endpoints. Develop a general strategy for handling and reporting these.

**Comment by SimonAnnetts** [comment]
Thinking about this one a little bit - currently for the mapInstance API endpoint if you request something that doesn't exist you will be returned a 404 error. Should this just be an empty object instead?
The Lookup endpoint and Gazetteer endpoints return empty arrays if the query returns nothing.
