### ISSUE TITLE
Geoserver config changes required for CORs

### ISSUE THREAD

**Issue by SimonAnnetts** [jncc/web-mapper-core#51]
Hi

There are changes that need to be made on your staging geoserver (and later on your production one too).
This is so that WMS images can be displayed on the mapper site which is using a different domain name.

The map at http://prelive.mapper.emodnet-seabedhabitats.eu/ is now using the web-API hosted at http://api.emodnet-seabedhabitats.eu/api/MapInstance
The api is querying your postgres database which has WMS references to http://staging.ows.emodnet-seabedhabitats.eu/emodnet/wms in the Layer test data. 

The layer images do not load because of CORs not being setup on your Geoserver.

You can see that on our test site http://jnccdev-map.esdm.co.uk/ 
that the images do load (from our geoserver). We have made the changes to our geoserver that I have documented within this Wiki page:

https://github.com/jncc/web-mapper-core/wiki/Tips-for-installing-geoserver-on-Ubuntu-16.04

It is likely that the X-Frame-Options will also need to be configured if you want to run your prelive mapper in an Iframe in your CMS. This is also documented here.

**Comment by paul-gilbertson** [comment]
@mattdebont are we hosting geoserver within tomcat on staging?

**Comment by paul-gilbertson** [comment]
@SimonAnnetts can you test this? I think it is working...

**Comment by SimonAnnetts** [comment]
I cannot test atm...
The web-api has died on ec2-63-34-227-23.eu-west-1.compute.amazonaws.com because it can no longer talk to the database. Please see issue #46 
This means that the web-map has no data.

**Comment by SimonAnnetts** [comment]
systemd seems to be trying to restart the web-api (as it should), but it fails to connect to the db

**Comment by SimonAnnetts** [comment]
Database access resumed..... now when I test - the staging geoserver does not seem to have CORs set still.

Image requests are still giving me this error in my webrowser:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://staging.ows.emodnet-seabedhabitats.eu/emodnet/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=eusm2016&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=3757032.814272985%2C6261721.357121639%2C5009377.085697313%2C7514065.628545967. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).[Learn More]

**Comment by paul-gilbertson** [comment]
According to my tests, all is fine now. Please retry.

**Comment by SimonAnnetts** [comment]
Ah I can see the problem.... the WMS service is tied down by IP restrictions. For some reason the web browser says it's a CORS issue when in actual fact it's getting a 403 from the WMS server!
It works fine if I VPN into the ESDM office and appear to come from that IP address.
Is it possible to add 87.127.21.54 (me) and 88.97.15.14 (James) as we work from home?

**Comment by paul-gilbertson** [comment]
Done. Please retry, and close if successful

**Comment by SimonAnnetts** [comment]
thanks
