### ISSUE TITLE
Finalise and implement styling and layout

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#52]
Discuss styling and layout with JNCC.
Implement styling.

**Comment by andyb-esdm** [comment]
@JordanPinder 
I've created a file called map-styles.css in the assets/css folder. This will be where you can edit and style the classes that I create.
This is how it looks so far to give you some idea.

![image](https://user-images.githubusercontent.com/31621682/53334768-9afc2380-38f1-11e9-85e0-0356567836e3.png)

So, for example, if you change .bg-primary to, say, red then all the elements in the mapper with that class will turn red. I expect there will be a lot more classes by the time we finish so I'll comment them as appropriate.

I'll deploy this to the test server later today I expect.

**Comment by andyb-esdm** [comment]
Forgot to mention. This is also where you can put classes to style your GetFeatureInfo templates. We'll provide some guidance for this.

**Comment by JordanPinder** [comment]
@andyb-esdm grand, thanks Andy! Looks nice and straightforward :)

**Comment by HelenwoodsJNCC** [comment]
How simple would it be to make the active layer menu movable? i.e. users can drag it to an alternate location?

**Comment by JordanPinder** [comment]
@andyb-esdm just checking whether guidance you mentioned has been produced? If so I'll close this issue.

**Comment by andyb-esdm** [comment]
@JordanPinder 
No I haven't. Plus there's more work to do on styling. There always is :) I suspect this will be the last issue to close!
I'll label this as ready for testing when I'm happy with everything, thanks.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm @SimonAnnetts Any idea why the mpa mapper group layers are being ordered in terms of their LayerGroupId rather than their assigned Order?

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm can we limit the reduce the horizontal limits of the map information box a bit? Currently for the MPA mapper it stretches most of the way across the map. Can you also remove the map-info works! comment above the top left corner.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC the incorrect sortorder is a bug - I'll fix it
I'll limit the width of the map-info control (and remove the default text too - sorry hadn't noticed it!)

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm thanks! Any idea how I can change the default base map to Bing maps? The base layers and map instance base layer api table options don't seem to reflect what is shown on the mapper.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC open street maps is hard-coded at the moment - we could maybe add a config setting this week. Will speak to @SimonAnnetts about that. I'm going to be revisiting base layers this week anyway.

**Comment by andyb-esdm** [comment]
okay

**Comment by JordanPinder** [comment]
@andyb-esdm Hi Andy, couple little design things some people have raised :) 

On the All Layers menu, is it possible for the sub-groups (light blue) to be slightly indented to the right so it is clear what group (dark blue) they're part of? A bit of padding should be fine I think?

When group names are more than one line, the second line does not align with the first (see picture). Is it possible to get these formatted so they align? 

![image](https://user-images.githubusercontent.com/30415162/56140622-29586180-5f93-11e9-8c39-3b379929a38b.png)

**Comment by GMDuncan** [comment]
hi @andyb-esdm Would it be possible to add the following to  feature-info-style.css ?

```css
table .confTable{
	text-align:center;
	margin:0 auto;
}

.hiConf{
	color: white;
	background-color: green;
}

.modConf{
	color: white;
	background-color: orange;	
}

.lowConf{
	color: white;
	background-color: red;	
}

.naConf{
	color: black;
	background-color: white;
}

td .confCell{
	width:90px;
	border:1px solid black;
	margin:0 auto;
}

.hidden{
	display:none;
}
```

**Comment by andyb-esdm** [comment]
@JordanPinder Yuck! I'll fix both of those alignment issues.

**Comment by andyb-esdm** [comment]
@GMDuncan Yes. I can add those. When development is completely finished, you will be able to add all the classes you like to these files (see documentation). I've ensured that these css files aren't cached so you will be able to edit them, refresh the browser and see your changes applied. But I'll add these in the meantime.

**Comment by GMDuncan** [comment]
@andyb-esdm Thanks! Just to test that I've done it correctly haha.

**Comment by JordanPinder** [comment]
@andyb-esdm just on the alignment, this is also present in the sub-grouping titles - is it possible to get the alignment fix filtered down to sub-groupings as well?

**Comment by andyb-esdm** [comment]
@JordanPinder I will indent all the things.

**Comment by andyb-esdm** [comment]
@JordanPinder I've fixed the word wrap and indented sub layer groups but not the layers beneath them. I can do this - and sort of think I should - but a bit concerned about space getting tight for the layer names. Before I edit the teetering pile of crockery that is the CSS, let me know what you think. I can always increase the default width of the whole layer selector if necessary too. Haven't deployed yet, so screenshot below.

![image](https://user-images.githubusercontent.com/31621682/56294609-386e1980-6123-11e9-97d7-9ef3c1f0c095.png)

**Comment by andyb-esdm** [comment]
Deployed here now - if you want to look at it live.
https://jnccdev-map.esdm.co.uk/

**Comment by GMDuncan** [comment]
hi @andyb-esdm I agree with you that indenting the layers more may well restrict the space too much. the dev site looks absolutely grand to me personally in terms of various levels of indentation. Awaiting views from the others, however!

**Comment by JordanPinder** [comment]
@GMDuncan just checking, when you say dev site do you mean the link above or the prelive site? 

Personally I prefer the indentation - if you were to increase the whole layer selector width by the level of indentation I'd assume that'd prevent any squashing?

**Comment by andyb-esdm** [comment]
@JordanPinder Yep. I can increase the width of the whole div and indent the layers to align with . The width was pretty arbitrary when I created the layer selector. 
However, I didn't want to mess with this before getting both of your opinions because when I did the first bit of indentation 'everything' went out of alignment temporarily (hence the crockery reference)

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm The indentation looks good to me!

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm have been thinking about all the elements in the bottom right corner of the mapper. I think if we rearranged so the base map attribute statement was at the bottom, i.e. where the lat/long box is at the moment and moved the lat/long up next to the scale bar it might look better. I think we could also remove the background box from the base map statement and just change the text colour - as this is less critical to the user experience. Can we also remove the redundant white space in the lat/long box? 
@JordanPinder any other thoughts?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Thanks for the feedback. I'll give it a try.
I found that, without any background, some of the controls were illegible against base mapping and the overlays but I'll experiment.

**Comment by JordanPinder** [comment]
@HelenwoodsJNCC @andyb-esdm I agree - switching the positions of the attribute statement & lat/lon box would be good, as well as removing the redundant white space. Although I'd personally be keen on keeping the background box for the base map statement - removing it might make it a bit difficult to view the text even if the colour is changed? Could always test it and see what it looks like :)

**Comment by HelenwoodsJNCC** [comment]
@JordanPinder @andyb-esdm im happy to keep the background on the base map attribute statement. It was just the element Hugh and I were least bothered about being really obvious!

**Comment by andyb-esdm** [comment]
@JordanPinder @HelenwoodsJNCC I've rearranged the controls on the bottom right of the map and deployed to the pre-live environments.

- Attribution for JNCC and background layers combined.
- Scale bar and mouse position combined
- Map controls at the top

**Comment by JordanPinder** [comment]
@andyb-esdm thanks Andy! All looking really nice :) do you know specifically where the JNCC attribution is on the mapper? Can't seem to find it, although it's more than likely me being blind!

**Comment by HelenwoodsJNCC** [comment]
@JordanPinder it will appear next to the base map attribution statement. There is one showing on the MPA mapper. I think you just need to add whatever your attribute statement is in the api Maps table.

**Comment by andyb-esdm** [comment]
Hi @JordanPinder I've put it next to the baselayer attribution. But I see that you haven't got an attribution message yet on the pre-live servers. You can customise the message in the configuration database. It's the column Attribution on table MapInstance.

For now, it's simply Made by JNCC on our test site.
https://jnccdev-map.esdm.co.uk/

![image](https://user-images.githubusercontent.com/31621682/56893586-0e99e880-6a7b-11e9-8e0a-ca0783981d31.png)

**Comment by JordanPinder** [comment]
@HelenwoodsJNCC @andyb-esdm thanks guys! Had a feeling I was just being a bit dense :)
