### ISSUE TITLE
Geoserver optimisation

### ISSUE THREAD

**Issue by JamesPe** [jncc/web-mapper-core#55]
To work on optimisation of geoserver - both in terms of building map caches and looking at optimising the vector data being used for the laters

**Comment by JamesPe** [comment]
@JordanPinder  can we arrange a time to have a preliminary chat about this next week?  Mon am or pm - I have another meeting at 12

**Comment by JamesPe** [comment]
Discussed various options and strategies on caching - summary in blog post here https://www.esdm.co.uk/configuring-geoserver-global-web-cache-gwc

**Comment by JordanPinder** [comment]
I've set off a test caching for the full detailed EUSeaMap (on staging GeoServer as "emodnet:eusm2016_caching_test") - seeding will apparently take ~4 hours or so, tiled to zoom level 12. 

I've changed the disk quota to 50GB for the time being - @paul-gilbertson do you have an idea what the max memory allocation is for the geoserver boxes?

**Comment by paul-gilbertson** [comment]
Machines are t2.medium, so 4GB.

**Comment by JordanPinder** [comment]
@paul-gilbertson we may need to think about increasing memory on the machines - if both the EMODnet & MPA data are being hosted on the same GeoServer instances then there's going some pretty large memory requirements. 

For reference I cached the main EMODnet layer last night at zoom scales 3 to 12 and it takes up ~1.8GB.

**Comment by JordanPinder** [comment]
@paul-gilbertson getting some issues with caching - one of the cached layers seems to have emptied and is not reseeding. Trying to [preview the layers](https://staging.ows.emodnet-seabedhabitats.eu/gwc/demo/emodnet:eusm2016_caching_test?gridSet=EPSG:4326&format=image/png8) results in an empty screen and returns an error of "No such workspace 'gwc/service'" when querying anywhere on the map. 

Any ideas what's causing this?

**Comment by JordanPinder** [comment]
@JamesPe @paul-gilbertson any ideas on the above comment?

**Comment by JamesPe** [comment]
Not sure @JordanPinder  - but possibly:

I got the same error No such workspace 'gwc/service' on GeoServer v2.14.0. It was because I had disabled Global Services, so GeoServer was expecting a path like /geoserver/<workspace>/gwc/service/wmts?. Obviously 'gwc/service' was being parsed as the workspace name, thus giving this error.

To fix:

In the web interface > Settings > Global > Under OGC Services, enable the checkbox for Enable global services

The problem is that in Tile Caching > Tile Layers selecting a Preview opens a new tab with /geoserver/gwc/demo/<workspace>:<layer>? which then makes tile calls to /geoserver/gwc/service/wmts? instead of /geoserver/<workspace>/gwc/service/wmts? which would have worked.

**Comment by JordanPinder** [comment]
@JamesPe amazing, thanks James - we recently turned off global services, just turned it back on and caching is working again. 

For reference [this thread](https://gis.stackexchange.com/questions/289401/geoserver-global-services-and-geowebcahe) might be useful - changing the Geowebcache endpoints needs to be done within the config file itself it seems. Will look into it further.

**Comment by JordanPinder** [comment]
@JamesPe @paul-gilbertson  me again! The cache is building on the layer but now the issue is it will not stop building - came in this morning and it was apparently taking up 1.25TB, whereas it should only be ~2GB max. 

I removed the layer and reuploaded from PostGIS, but now getting a disk quota issue (see attached). 

![GeoServerError](https://user-images.githubusercontent.com/30415162/55225739-380ced80-520b-11e9-931f-78b3c192379c.PNG)

Could worth removing the diskquota.index.db file ([per this suggestion](http://osgeo-org.1560.x6.nabble.com/Tile-Caching-Quota-Store-Problem-td5054880.html#a5055135))?

**Comment by JamesPe** [comment]
Welcome to the joys of geoserver !  
I've not seen that one before - but the suggestion sound sensible
Our experience with geoserver is that when its running ok - all is well - but when it starts going amiss its often easier to reset that element and rebuild - so that suggestion sounds sensible

**Comment by JordanPinder** [comment]
@paul-gilbertson have you had any chance to look further into this, specifically removing the diskquota.index.db file from the staging GeoServer VM?

**Comment by paul-gilbertson** [comment]
Done, retry?

**Comment by JordanPinder** [comment]
Error is still coming up unfortunately!

**Comment by paul-gilbertson** [comment]
Try now....

**Comment by JordanPinder** [comment]
Same as before, saying the same error as usual :(

**Comment by JordanPinder** [comment]
FYI the error seems to be resolved now, error message no longer appearing and disk storage information is appearing again. Thanks for sorting it!

**Comment by JordanPinder** [comment]
Hi @JamesPe , sorry to come back to this so late in the year! I've just got a couple queries about WPS. 

Within EMODnet there is an increasing need to facilitate the "seamless" dissemination of data to end users. Currently we don't provide WPS to users given it's often intensive computational requirements, but to meet this objective we may need to provide WPS in some instances. 

I was wondering if Exegesis have had any previous experience in providing WPS operations / data? If so, do you have general recommendations for doing so?

**Comment by JamesPe** [comment]
Hi @JordanPinder - I'm afraid I have never used WPS in geoserver - sorry.

I can ask around amongst our devs in case anyone else has - but I don't think it's something we've used.

Could you give us an example of what you are actually trying to achieve ?

**Comment by JordanPinder** [comment]
@JamesPe I guess it would mainly be focused on geometric processing (i.e. clipping, intersect two different layers etc.), but also potentially process chaining.
