### ISSUE TITLE
Set a maximum tile zoom level for a map instance

### ISSUE THREAD

**Issue by JamesPe** [jncc/web-mapper-core#56]
Looking at some of your data I think this makes sense to prevent user from zoomin in too far.  e.g. looking at eusm2016 the blocks that its made up from appear to be about 100m across.  This suggests that tile level 12 is probably the maximum it makes sense to goto.  
Obviously you would want to check the resolution of other data being presented on the map.
This is important - not only for the look of the map - but also for caching.   Every step is is 4x the size of the previous layer so you can save a lot of processing time and disk space by limiting at appropriate scale.

We would need to add a setting into the map config - but easy to do

**Comment by HelenwoodsJNCC** [comment]
This is likely to be more relevant to layers on the emodnet mapper than the MPA mapper but It makes sense to me to limit the zoom. @JordanPinder what do you think?

**Comment by JordanPinder** [comment]
I agree with limiting the resolution but I would need to check the fine-scale layers, i.e. habitat maps from survey.

**Comment by JamesPe** [comment]
It will be a configurable setting for the map so you can adjust it.  We just need to add the setting. @andyb-esdm @SimonAnnetts

**Comment by andyb-esdm** [comment]
This still needs to be implemented

**Comment by SimonAnnetts** [comment]
MapInstance now has a MaxZoom property.
https://github.com/jncc/web-mapper-core/wiki/Database-Schema-and-API-Endpoints
