### ISSUE TITLE
Create some real map layers

### ISSUE THREAD

**Issue by JamesPe** [jncc/web-mapper-core#57]
Following on from the session on caching it would be useful to have some "real" layers setup that we can configure against the map.
Now we have discussed caching it would make sense if at least some of these included a cache and perhaps only one layer (as opposed to the group family)

**Comment by andyb-esdm** [comment]
It would also be good to have some real filters. Currently we have a working lookup for EUNIS but I haven't been able to test multiple filters on a layer yet. Can provide details to whoever will do it.
