### ISSUE TITLE
getFeature Info style

### ISSUE THREAD

**Issue by JamesPe** [jncc/web-mapper-core#59]
We need a decision on whether you would like this to be a modal popup (as in emodnet mapper) or a panel at the bottom on the current version of the new mapper

**Comment by JordanPinder** [comment]
@JamesPe popup window would be my preference - @HelenwoodsJNCC what about you?

**Comment by HelenwoodsJNCC** [comment]
@JamesPe @JordanPinder pop-up would be my preference too.

**Comment by andyb-esdm** [comment]
Popup it is then. It will look a little like the filter popup with an internal scrollable window if there are multiple layers.

**Comment by HelenwoodsJNCC** [comment]
Great thanks

**Comment by andyb-esdm** [comment]
@JordanPinder @HelenwoodsJNCC 
At the moment, just clicking on the map gets the feature info. Should this be a toggle-able  tool on the toolbar or activated by right click? Or are you happy with the current behaviour?

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm I think it is fairly intuitive at the moment, and I think it might get forgotten about as a tool on the side. @JordanPinder do you feel strongly either way?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Thanks. Just wanted to check before I finalise this.

**Comment by JordanPinder** [comment]
@HelenwoodsJNCC @andyb-esdm I agree, current setup is nice and simple - moving to a toolbar may mean it's forgotten.

**Comment by GMDuncan** [comment]
Something (angular?) seems to be pulling through the title text in the getfeatureinfo header ("Geoserver GetFeatureInfo output") as text within a div at the top of the Feature Info panel.  Is there any way to prevent this?

**Comment by andyb-esdm** [comment]
It wasn't angular it was andyb ;)
I was displaying the whole returned document as the innerhtml of the div for each feature info.
I've now used the DOMParser to extract just the body from the getfeatureinfo response and use that as the innerhtml.
Please test.

**Comment by HelenwoodsJNCC** [comment]
I have just tested and the text no longer appears.

**Comment by GMDuncan** [comment]
Looks fine here too. I'm not sure if it's changed now that just the body is loaded, or my brain has gone on to ultimate nitpick mode, but it seems like the padding inside of the featurinfo panel has disappeared (or was never there and I'm imagining things...) 

Would it be possible to add a little bit of padding (5-10px) to the inside of the panel just to stop the featureinfo text from sitting right on the edge?

*(Low priority change)*

**Comment by andyb-esdm** [comment]
Certainly can do that. I wouldn't have thought the change to body only would have affected this but will pad a little in the pane.
