### ISSUE TITLE
Permissions for JNCC

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/web-mapper-core#60]
1.	I’m having a couple problems with permissions on the new account setup a few weeks ago. 
I’m trying to access a table called “habitatmaps” within the emodnet_staging database under the “wp5” schema. This table was created under the previous PostGIS account (i.e. jncc_emodnet_admin), and my new account doesn’t have the correct permissions to alter it. I think I was allowed blanket permissions to the database for my new account but I’m not sure if they’ve all gone through correctly. 
2.	access to the configuration database within the emodnet server, namely “emodnet_web_api”.
3.	both have access to the mpa_web_api config database

**Comment by JordanPinder** [comment]
@LynnHeeley @mattdebont is this still on your radar guys? The configuration for the EMODnet layers needs doing today/tomorrow so need access granting to emodnet_web_api.

**Comment by SimonAnnetts** [comment]
@LynnHeeley @mattdebont @JordanPinder 
I seem to have permission problems now too.
The emodnet_web_api user has lost Delete permissions and possibly insert permissions on the tables:
Map, LayerGroups, Layers and ExternalWmsUrls

The web-api needs this to insert and delete test data from the database. Once we finish testing we can switch to the readonly user.

**Comment by SimonAnnetts** [comment]
@LynnHeeley @mattdebont @JordanPinder
Ah I see the problem:
The web-api created a new table: 'ExternalWmsUrl' but the permissions look wrong so my code to populate the DB is failing.
Here are the permissions on other tables:
~~~
emodnet_web_api=> SELECT grantee, privilege_type
FROM information_schema.role_table_grants
WHERE table_name='Layer';
           grantee           | privilege_type
-----------------------------+----------------
 emodnet_web_api_admin_role  | INSERT
 emodnet_web_api_admin_role  | SELECT
 emodnet_web_api_admin_role  | UPDATE
 emodnet_web_api_admin_role  | DELETE
 emodnet_web_api_admin_role  | TRUNCATE
 emodnet_web_api_admin_role  | REFERENCES
 emodnet_web_api_admin_role  | TRIGGER
 emodnet_web_api_reader_role | SELECT
 emodnet_web_api_writer_role | INSERT
 emodnet_web_api_writer_role | SELECT
 emodnet_web_api_writer_role | UPDATE
 emodnet_web_api_writer_role | DELETE
 jncc_root_user              | INSERT
 jncc_root_user              | SELECT
 jncc_root_user              | UPDATE
 jncc_root_user              | DELETE
 jncc_root_user              | TRUNCATE
 jncc_root_user              | REFERENCES
 jncc_root_user              | TRIGGER
(19 rows)
~~~

and here is the permission on the newly created table:

~~~
emodnet_web_api=> SELECT grantee, privilege_type
FROM information_schema.role_table_grants
WHERE table_name='ExternalWmsUrl';
     grantee     | privilege_type
-----------------+----------------
 emodnet_web_api | INSERT
 emodnet_web_api | SELECT
 emodnet_web_api | UPDATE
 emodnet_web_api | DELETE
 emodnet_web_api | TRUNCATE
 emodnet_web_api | REFERENCES
 emodnet_web_api | TRIGGER
(7 rows)
~~~

**Comment by SimonAnnetts** [comment]
This is working now. The permissions have changed.

**Comment by SimonAnnetts** [comment]
@JordanPinder
Not sure if you are still having issues with permissions when trying to populate the database.

If it's of any help to you I have created some very basic (and temporary) web pages that let you put data into the database. There's no authentication or protection for them or anything like that, so we can't use them in production without further work, but it might speed up how you get some real data into the database. Please have a look at:
https://api.emodnet-seabedhabitats.eu/Index1 and use the links along the top for managing data in each of the tables. You will find that I have already populated the gazetteer.

**Comment by JordanPinder** [comment]
@SimonAnnetts permissions were granted yesterday so seems to be working. Thanks for the web page, that's exactly what I was needing to compare the layer configuration! Should have most things pulled in by tomorrow afternoon.

**Comment by SimonAnnetts** [comment]
Great. and we can remove the test data very easily.... all the names of things end with '(Test)' ;)

**Comment by andyb-esdm** [comment]
@JordanPinder does that buy me a bit more time to add polish to the mapper in the morning?

**Comment by JordanPinder** [comment]
@andyb-esdm of course! Polish away :)

**Comment by andyb-esdm** [comment]
@JordanPinder Thanks very much :)

**Comment by JordanPinder** [comment]
@LynnHeeley just tried using a blanket copy statement in the emodnet_web_api database and I'm getting another permissions issue using the following:

COPY public.Layer FROM 'file/path/to/Layer.csv' WITH (FORMAT csv);

Says I need to be a superuser? 

I'm assuming this is me being a bit dense so apologies if I've missed something.

**Comment by mattdebont** [comment]
@JordanPinder COPY requires you to have the file on the remote machine, which you do not have access to so what you are seeing is a filesystem error.

You will need to use a psql /copy command to do this, more infor here: https://til.codes/using-postgres-copy-command-to-copy-data-from-one-server-to-another/ or do the import in a different way here

**Comment by JordanPinder** [comment]
Closing as issue resolved.
