### ISSUE TITLE
Dot Net Core environment on your web-api server via systemd

### ISSUE THREAD

**Issue by SimonAnnetts** [jncc/web-mapper-core#61]
I'm running into issues running database migrations when updating the web-api and the database schema on your server.
@paul-gilbertson is it possible to change the environment variable that is set in the systemd config for the web-api from:
~~~
Environment=ASPNETCORE_ENVIRONMENT=Production
~~~
to
~~~
Environment=ASPNETCORE_ENVIRONMENT=Development
~~~
so that I can see the stack traces when it fails. We can change it back when development is complete.
For some reason the web-api cannot insert or delete records into some tables after it has done a database migration and updated the schema.

**Comment by paul-gilbertson** [comment]
Actioned. Please test, then close.
