### ISSUE TITLE
Additional layer info

### ISSUE THREAD

**Issue by HelenwoodsJNCC** [jncc/web-mapper-core#64]
@andyb-esdm Would it be possible to integrate the info contained within the MetadataDescription of the Layers api table somewhere, just to give the user more info about the layer without having to click on the metadata link. This info appears on the current mappers when you hover over the ? button beside each layer name. @JordanPinder i think we discussed having it appear when you hovered over the layer name?

**Comment by andyb-esdm** [comment]
Yes. We could display it when you hover over the metadata button?

**Comment by HelenwoodsJNCC** [comment]
The only issue I see it that users might want the additional info when deciding if they want to use the layer i.e. before they turn on the layer and it moves into the active layer pane with the metadata button. I think we discussed moving some of the buttons i.e. metadata and download into the all layers pane which would work with the above.

**Comment by andyb-esdm** [comment]
Oh I see what you mean - sorry! I'll do something with the layers panel.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC  I've added a question mark icon and tooltip to display the metadataDescription field of the layer configuration.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm I like it, thanks.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Oops - there was a little bug. If there was no metadata description, you still got the icon and an empty tooltip. This applied only to external layers on our configuration. Now fixed.

**Comment by JordanPinder** [comment]
Closing as issue is resolved.
