### ISSUE TITLE
Finalise staging and Live environments for MPA and Emodnet - Matt

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/web-mapper-core#66]
EC2 instance needs to be replicated

**Comment by JordanPinder** [comment]
@paul-gilbertson Hi Paul, have you got any indication on when the live EMODnet mapper and config database will be completed?

**Comment by paul-gilbertson** [comment]
March 29th

**Comment by LynnHeeley** [comment]
Emodnet complete. MPA not ready

**Comment by GMDuncan** [comment]
https://staging.api.emodnet-seabedhabitats.eu is (i think) currently accessing the "emodnet_web_api" database rather than "emodnet_web_api_edit"

(This is cascaded through to https://staging.mapper.emodnet-seabedhabitats.eu as this uses the api above to access layers)

Is this intended or does someone (not sure who) need to change the "staging" api to run off the "edit" database? (actually not sure!)

**Comment by GMDuncan** [comment]
The emodnet_web_api_edit database is also blank, but this can be rectified with a database dump and restore I would think

**Comment by SimonAnnetts** [comment]
This may be something that we did by accident, not knowing which db the staging sites should running off.

When we deploy from our dev environment to your staging, we also deploy the config file which sets up the database connection details for the web-api. Currently we send these for Emodnet and MPA (I have removed the password strings)

Emodnet:
~~~
    "ConnectionStrings": {
      "JNCCWebApiDatabase": "Host=jncc-spatial.c9k3pg5plo3u.eu-west-1.rds.amazonaws.com;Database=emodnet_web_api;Username=emodnet_web_api;Password=*****;SSL Mode=Require;Trust Server Certificate=true"
    },
~~~

MPA

~~~
    "ConnectionStrings": {
      "JNCCWebApiDatabase": "Host=jncc-spatial.c9k3pg5plo3u.eu-west-1.rds.amazonaws.com;Database=mpa_web_api;Username=mpa_web_api;Password=*******;SSL Mode=Require;Trust Server Certificate=true"
    },
~~~

Please let me know if some of these settings should be different for the staging servers in the configs we hold
*OR*
if you want us to stop sending the config file when we deploy changes from our dev environment to your staging servers

thanks

**Comment by jonparsonsjncc** [comment]
Check with team if this has now been resolved

**Comment by GMDuncan** [comment]
hi @jonparsonsjncc , staging.api still seems to be pulling its  data from the emodnet_web_api database. 

The emodnet_web_api_edit database is currently empty (pending a dump/restore of the live db), so heading to https://staging.api.emodnet-seabedhabitats.eu/Layers should result in no layers being listed.

**Comment by HelenwoodsJNCC** [comment]
@jonparsonsjncc As far as I am aware a staging version of the MPA mapper hasn't yet been set up. We have only the live version here:https://mapper.mpa.jncc.gov.uk/. I know Paul had the SSL certifcates set up (see #47) but im not sure how far things got after that.

**Comment by paul-gilbertson** [comment]
I will pick this up tomorrow
