### ISSUE TITLE
GetFeatureInfo feature_count

### ISSUE THREAD

**Issue by GMDuncan** [jncc/web-mapper-core#67]
Mapper calls to getFeatureInfo requests do not specify a feature_count value in the querystring, Geoserver's default feature_count is 1, meaning that in layers which have overlapping features, only the topmost gets returned.

Noticed through the WP4 points layer which has duplicate points (one for each classification system).

Is it possible to have this either controllable through the mapper administrative interface (either backend or API), or set to a fixed value? 

Somewhere between 5 and 10 seems sensible to me, but open to suggestions!

**Comment by andyb-esdm** [comment]
Didn't know about this. If it isn't something you would want to change can we set it to a high constant e.g. 50 so we know we will always get 'everything'? Alternatively, it could be in the map config of the api or in the json config file config.prod.json on the server.
Shall we try it with a constant first to see if that's enough?

**Comment by andyb-esdm** [comment]
I've added feature_count = 50 by default. I've pushed to live. So you may need to refresh your browser.

**Comment by GMDuncan** [comment]
Can confirm this is pulling through max 50 records now. Thanks.

**Comment by JordanPinder** [comment]
@andyb-esdm I think a high-constant would be fine as I can't imagine this would need changing in the future. @HelenwoodsJNCC do you agree?

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm @JordanPinder yes, a high constant is fine.

**Comment by JordanPinder** [comment]
Grand, closing :)
