### ISSUE TITLE
Access to basic CRUD pages for database management

### ISSUE THREAD

**Issue by SimonAnnetts** [jncc/web-mapper-core#69]
Currently the web-api has a very basic set of CRUD pages which can be used to populate the database with map instance and layer data etc. We used these for testing and development.

The URL is https://api.emodnet-seabedhabitats.eu/Index1

The interface has not been worked on in any way to make it more useable - for example the Layers list page has so many fields that the page is too wide etc.

**This interface is also currently not protected in any way.** 

There are a number of options, depending on whether you think that this interface is useful, or whether going forward you are happy to edit the data in the database directly using other tools.

1) We remove this interface from the web-api completely just before launch
2) You protect the URL(s) used by this interface in the Apache proxy server config by limiting access to certain IPs only for any URL except /api/*
3) You protect the URL(s) used by this interface in the Apache proxy server config by enabling basic HTTP authentication for any URL except /api/*
4) We could do further work on this interface (currently outside of the scope of this project) to 
a) tidy it up and make the interface more useable
b) to provide perhaps an inbuilt authentication system (with another table in the DB for users)

**Comment by paul-gilbertson** [comment]
My preference is option 2 from the list above
