### ISSUE TITLE
Schema change to emodnet-web-api database and Backups

### ISSUE THREAD

**Issue by SimonAnnetts** [jncc/web-mapper-core#72]
Hi,

I'm about to make some minor schema changes to the web-api database. This will happen when we upload the latest web-api code version to your server - it will perform some database migrations. 
There shouldn't be any data loss, but I don't want to take any risks!
Now that you have some real data in the database I would prefer to wait until you have a backup of the database. Can this be arranged?

**Comment by SimonAnnetts** [comment]
@JordanPinder can I go ahead and update the schema of this database before Paul copies it? You have real data in there that was for UAT, should it be backed up first? I'm not expecting it to be lost, but would feel safer if we had a copy.

**Comment by JordanPinder** [comment]
@SimonAnnetts Sorry Simon!! Completely forgot to reply to this yesterday - I'll do a SQL dump of the database just in case, will let you know when it's fine to update the schema.

**Comment by JordanPinder** [comment]
@SimonAnnetts database copied - ran into issues with permissions on sequences, took a while to figure an alternative solution. 

Feel free to update the schema!

**Comment by SimonAnnetts** [comment]
Done!
