### ISSUE TITLE
MPA mapper polygon load issue

### ISSUE THREAD

**Issue by HelenwoodsJNCC** [jncc/web-mapper-core#74]
We are having a bit of an issue with some of the MPA polygons, whereby they only partially displaying when zooming in close, specifically those with complex inshore boundaries, e.g. Strangford Lough SAC. @JamesPe any ideas why this is? Thinking it might be something that could be solved by caching the layer potentially?

![image](https://user-images.githubusercontent.com/30657820/55796121-1dffc480-5ac1-11e9-87d3-bbd2e9edbe44.png)

**Comment by JamesPe** [comment]
Hmm - are they all polygons - or are some lines etc ?  I assume they are all one layer in geoserver?
Is it a timeout issue - that geoserver is failing to keep up?
@HelenwoodsJNCC  can you send me a permalink highlighting the issue ?
Also just possible its a network connectivity issue at your end - but again if I could see that would help identify

**Comment by HelenwoodsJNCC** [comment]
@JamesPe they are all polygons and in a single layer on Geoserver. 

Here is an example: 
https://mapper.mpa.jncc.gov.uk/?zoom=10&center=-5.544,54.430&layerIds=43&baseLayerId=1&activeFilters=

**Comment by JamesPe** [comment]
Hmm - very odd - but definitley geoserver.

If you ask for the full none tiled image - you get it it e.g
https://staging.ows.emodnet-seabedhabitats.eu/mpa_mapper/wms?mapInstance=MPSMap_&LAYERS=sac_mc_full&FORMAT=image%2Fpng&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-712952.72422874,7214697.2527581,-538332.33313556,7301262.1872789&WIDTH=2284&HEIGHT=1132

However if you ask for a tile you can get part of the image (e.g the coastal image but missing strangford)

https://staging.ows.emodnet-seabedhabitats.eu/mpa_mapper/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng8&TRANSPARENT=true&LAYERS=sac_mc_full&TILED=TRUE&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-626172.1357121654%2C7240115.319171894%2C-587036.3772301552%2C7279251.077653904

**Comment by JamesPe** [comment]
I can get the same effect here directly in geoserver- https://staging.ows.emodnet-seabedhabitats.eu/mpa_mapper/wms?service=WMS&version=1.1.0&request=GetMap&layers=mpa_mapper:sac_mc_full&styles=&bbox=-2155423.5,6417485.5,374296.3125,8592683.0&width=768&height=660&srs=EPSG:3857&format=application/openlayers

Zooming in at steps and at one zoom level strangford disappears.
I can only imagine its a bad polygon at a certain zoom level

**Comment by JamesPe** [comment]
@HelenwoodsJNCC  been messing with your caching settings for that layer.
Changing the metatiling settings for the cache has improved (but not removed) the issue.
I'm pretty sure that this means its probably a n issue with a multipart polygon / index - i.e. the polygon isn't showing on the tile because geoserver/postgre doesn't believe the polygon exist on that tile.

I don't have access to your postgre db fro MPA mapper - so not much more I can do at that - but hopefully tahts pointed you in the right direction

**Comment by JamesPe** [comment]
https://gis.stackexchange.com/questions/170009/multipolygon-postgis-layer-exposed-via-geoserver-is-empty-at-certain-zoom-levels

https://stackoverflow.com/questions/21719941/postgis-convert-multipolygon-to-single-polygon

**Comment by HelenwoodsJNCC** [comment]
@JamesPe thanks, will do some investigating in the db.

**Comment by HelenwoodsJNCC** [comment]
@JamesPe Turns out the data had been imported with a simple polygon geometry type rather than multipart polygon geometry type. I have fixed this for the SAC layer and it seems to work ok now.
