### ISSUE TITLE
Dropdown for pre-configured external layer sources

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#75]
@HelenwoodsJNCC @JordanPinder
Created a new issue because there was something I missed (I think Helen and James spotted it).
You can configure external WMS sources in the database and these are made available via the API. The original EMODnet provides this.
I've implemented this now. Click 'add external layer'. If there are any external WMS configured, you can select one, get the layers available for it and add them to the map.

![image](https://user-images.githubusercontent.com/31621682/56884217-ff0da600-6a60-11e9-84e8-71ca39c2fd3a.png)

**Comment by JordanPinder** [comment]
@andyb-esdm hi Andy, just been playing around with some Sentinel-2 data and came across an interesting bug (sorry!). 

Using the following WMS (https://services.sentinel-hub.com/ogc/wms/8ed2dbed-6b26-43d6-9fae-d7f9c26b83a6?) I pulled in a layer, but when selecting it to be active it seems to activate an EMODnet layer already configured in the API (see below). 

![Sentinel_WMS_error](https://user-images.githubusercontent.com/30415162/57028089-18b41680-6c36-11e9-9e3a-336ea010fc43.PNG)

Do you know why this might be happening?

**Comment by JordanPinder** [comment]
Looking a little bit more it seems some external WMS formats aren't available in png8, see example which is available in png:

https://services.sentinel-hub.com/ogc/wms/8ed2dbed-6b26-43d6-9fae-d7f9c26b83a6?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=BATHYMETRIC&TILED=TRUE&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-195678.7924100496%2C7269467.138033403%2C-185894.85278954703%2C7279251.077653905

**Comment by andyb-esdm** [comment]
@JordanPinder I'm not getting an EMODnet layer already configured in the API. But I am getting an error when selecting that geology layer. But note it still says it's the Geology layer. I'll address your second question in another reply but can you confirm you don't get a pre-configured layer when you select an external layer? If so, that's going to be some nasty bug around layerIds

![image](https://user-images.githubusercontent.com/31621682/57030915-22da1300-6c3e-11e9-938e-40b4f9aa97ce.png)

**Comment by andyb-esdm** [comment]
@JordanPinder Yes. I think you're right about PNG8 support because the error response is 'invalid format' and you've shown it's fine with PNG.
I think, to be safe, we could request all external layers as PNG to avoid this (alternatively, we could query the GetCapabilities response but that's not so nice).
So would default PNG for all external layers be okay?

**Comment by andyb-esdm** [comment]
@JordanPinder Setting the default format to image/png for external layers works.
I've updated our (ESDM) test website but haven't pushed to pre-live due to the embargo.

![image](https://user-images.githubusercontent.com/31621682/57032115-7e59d000-6c41-11e9-8358-c3e2e33194ae.png)

**Comment by JordanPinder** [comment]
@andyb-esdm I think the layer bug might only be on the prelive site - the EMODnet LayerId for the layer in my example is 1014, does the API generate a temporary LayerId for the external layers? If so would it be the default value that is set for them?

PNG for all external layers would be fine with me - they seem to be enabled for most WMS. We'll let you know when it's OK to push the changes after the embargo.

**Comment by andyb-esdm** [comment]
@JordanPinder to my eternal shame ...
![image](https://user-images.githubusercontent.com/31621682/57063065-11365100-6cba-11e9-8f2e-f1300398f9fe.png)

**Comment by andyb-esdm** [comment]
@JordanPinder I must have been hoping to avoid getting the max layer id from the existing layers because it's quite a 'long way' from the LayerService in code. But looks like I'll have to do this to ensure no id clashes. I'll let you know when a fix is in place.
Apologies.

**Comment by JordanPinder** [comment]
@andyb-esdm understandably! It's just the way I've set up the LayerId's which is the issue :)

**Comment by andyb-esdm** [comment]
@JordanPinder that's very nice of you to say so. But I'm the one who created the magic number ;) Will be in touch soon.

**Comment by andyb-esdm** [comment]
@JordanPinder I've changed this to pick up the max layer id and max layer group id instead of using 999 upwards to prevent id clashes. I've deployed to https://jnccdev-map.esdm.co.uk/
Again let me know when/if to deploy to emodent/mpa pre-live.

**Comment by JordanPinder** [comment]
@andyb-esdm brilliant, thanks for the quick turnaround on this Andy! I'll post in #77 when it's fine to deploy any changes.

**Comment by andyb-esdm** [comment]
@JordanPinder If you'd like to do some testing in the interim on our mapping server (e.g. adding external layers etc.) Feel free.
