### ISSUE TITLE
Last minute change

### ISSUE THREAD

**Issue by SimonAnnetts** [jncc/web-mapper-core#76]
@GMDuncan @JordanPinder @HelenwoodsJNCC @paul-gilbertson

Sorry Guys,
I had to make one final change to the web-api this morning to fix a small bug I had discovered. I have deployed to your staging servers. I hope it's not too late for you to copy everything to live. Can you please also just confirm that everything still works as expected? I did try the mappers - the MPA map starts up with none of the layers visible which seems to match the config, so does the Emodnet map, but I can no longer see the CRUD pages for this to check if this is also configured this way.

**Comment by SimonAnnetts** [comment]
I have broken something.... I think I've overwritten the config file for the MPA api with the emodnet one. I'll get this fixed asap!

**Comment by HelenwoodsJNCC** [comment]
@SimonAnnetts the MPA mapper should have lots of layers showing but for some reason none are anymore. I am getting a 404 on the following request url: https://api.mpa.jncc.gov.uk/api/mapinstance/MPA. When I check the mapper CRUD page it seems to have been overwritten with EMODnet data, but the underlying API database is ok

**Comment by GMDuncan** [comment]
Hi @SimonAnnetts , the live deployment is currently planned to be before lunch, if you can let us know when it's resolved (or if it wont affect EMODnet deployment), that would be great :)

**Comment by SimonAnnetts** [comment]
@HelenwoodsJNCC, OK, I've re-instated the MPA web-api's config file. It was logging in to the database as the emodnet user and using the emodnet database. Does this look better now?

**Comment by HelenwoodsJNCC** [comment]
@SimonAnnetts All looks ok again now, thanks.

**Comment by SimonAnnetts** [comment]
@GMDuncan, can you confirm that the emodnet map still looks as it should? I was surprised that there are no layers set to visible when you first load the map.

**Comment by andyb-esdm** [comment]
@SimonAnnetts that's the way the current emodnet web mapper works too

**Comment by GMDuncan** [comment]
@SimonAnnetts the map seems to be loading as expected for me, @JordanPinder can you confirm?

I can also confirm that it is intentional/wai to have no layers set to visible on mapload!

**Comment by JordanPinder** [comment]
@SimonAnnetts all working fine with me, and mapper is intentionally set with no layers on load :)

**Comment by SimonAnnetts** [comment]
Ok, phew.... thanks and big apologies again for this mishap this morning with the config file.

**Comment by GMDuncan** [comment]
No worries! Thanks for the quick fix!

**Comment by andyb-esdm** [comment]
We'll discipline him internally.

**Comment by GMDuncan** [comment]
Fetch....The comfy chair!
