### ISSUE TITLE
Tile/WMS image queue not culled on map move

### ISSUE THREAD

**Issue by GMDuncan** [jncc/web-mapper-core#80]
Potential high priority fix here.

When a user moves through the map as tiles are being requested, existing tile requests are not removed.

This is potentially resulting in large stacks of requests on the geoserver instance as a user moves around the map, as the tiles for the new areas (or zoom levels) are continuously added.

Is it possible to, on end of user interaction (zoom, pan) truncate the current tile queue and re-request tiles? Presumably tiles already rendered would then be pulled from the user's cache?

@ulric-wilson just checking that I have this correct?

**Comment by andyb-esdm** [comment]
@GMDuncan @ulric-wilson @JamesPe @SimonAnnetts 
I've looked into this and I'm sorry but not sure what I can do to help with it.
Currently the map has properties loadTilesWhileAnimating and loadTilesWhileInteracting set to false.
You can test this by:

- refreshing the map page
- opening network tab
- letting all activity in the network tab cease
- clearing the network tab
- click and hold on the map
- drag the map
- release the mouse button

You should see that no tiles load while you are dragging.

Similarly, refresh the map page and use the gazetteer. No tiles are loaded until the animation stops.

As I understand it, if a user zooms, pauses, pans, pauses etc. OpenLayers makes requests to Geoserver for the tiles but, once these http requests are made to the server, you can't (easily?) abort them.

This is discussed in an (old) issue here:
https://github.com/openlayers/openlayers/issues/5532
and is apparently fixed to some extent here:
https://github.com/openlayers/openlayers/pull/6939

But there doesn't seem to be any other option open to us for changing the behaviour further.

I'm happy to be corrected on any of this and implement any fix that you feel might work.

![image](https://user-images.githubusercontent.com/31621682/57608740-6d745d00-7565-11e9-9b77-f9ce763a9254.png)

**Comment by GMDuncan** [comment]
Hi @andyb-esdm . No worries - yes, I was wondering about #6939 in openlayers, but wondered if it had been implemented in the version that we're using, as it seemed to do exactly what's needed (aborting disposed tiles). Is that the case that our version of openlayers should include this feature?

 If so, you're right, it appears that there's not much extra that can be done, and I'll close the issue :)

**Comment by GMDuncan** [comment]
Happy with that! :) It seemed in some way like bullet 2 was what was happening (queued tiles that were not relevant were still being requested), but likely an error on my part. 

I'll keep testing on the off-chance that it's a bug with the fix, but either way, it's not something that can be solved here so i'll close the issue :)

**Comment by andyb-esdm** [comment]
Okay. Please let me know if you find it is bullet 2 that's occurring.
