### ISSUE TITLE
Measurement tools

### ISSUE THREAD

**Issue by HelenwoodsJNCC** [jncc/web-mapper-core#83]
Is it possible to add simple measurement tools to the mapper e.g. distance/area

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC 
Yes it is. Example here: https://openlayers.org/en/v4.6.5/examples/measure.html
There isn't a measurement tool as such but you can draw a vector on the map, calculate and report its length/area. Would take a few hours to create a nice user interface component for this.

**Comment by HelenwoodsJNCC** [comment]
Closing for now - to be investigated at a later date.
