### ISSUE TITLE
Zoom to coordinates

### ISSUE THREAD

**Issue by HelenwoodsJNCC** [jncc/web-mapper-core#84]
Addition of a zoom to xy coordinates tool - is there something easily available via OpenLayers?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC There isn't a control, as such, but it's very easy to do. You would just need an input (or two if you want to enter lat and long separately) and then you can zoom the  map to those coordinates. Time estimate to implement, test and deploy would be two to three hours.

**Comment by HelenwoodsJNCC** [comment]
Closing for now - to be investigated at a later date.

**Comment by HelenwoodsJNCC** [comment]
Can we start looking into this one once the mixed filtering issue is resolved.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Sure.
How about up in the top right, close to the gazetteer with separate lon and lat inputs. Hitting enter/pressing a button, zooms you to the coordinates. Should it always be visible or opened from a button on the controls bar?

**Comment by JordanPinder** [comment]
Apologies for not clocking this! @HelenwoodsJNCC @andyb-esdm I like the position next to the gazetteer, also agree with Helen that opening from a button would be preferable.

**Comment by andyb-esdm** [comment]
Okay. Will get on to it next. By the way mixed filters are done (bar jncc testing) and Simon has done the server-side proxy so I'll build on that soon. So there will be a few new features for your next version.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @JordanPinder @GMDuncan
I've implemented this feature and deployed to https://jnccdev-map.esdm.co.uk/
There's a crosshair icon on the right of the bottom toolbar. Clicking it opens the 'goto lon/lat' window.
Can you give it a test and let me know if this meets the requirement. Then I'll deploy to the MPA staging. Do you also want me to deploy to the EMODnet staging.
Changes in this version are:
(Upgrade to Angular 8)
Fix for IE11 JavaScript compatibility (includes vs indexof)
Support for mixed filters (note this needs testing with a 'real' mixed filter)
Goto Lon/Lat

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm I have tested and it works ok. The only thing I would change the name in the box to 'Go to Longitude/Latitude' and the abbreviation from 'Lon' to 'Long'

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC okay - do you want any help text on there e.g. enter coordinates in decimal degrees?

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm yes if you could add the help text to specify decimal degrees that would be great.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Okay those changes are made. Shall I deploy to MPA staging now?

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm yes happy for you to deploy now. Thanks

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC 
Okay. Done. Will hold off deploying to EMODnet until I hear back.
Closing issue.

**Comment by GMDuncan** [comment]
Not sure of any implications on the emodnet-side of things - are there any custom configurations there @JordanPinder ? Also not sure if it has any implications to the staging and live using the same config?
