### ISSUE TITLE
Staging GeoServer issues

### ISSUE THREAD

**Issue by JordanPinder** [jncc/web-mapper-core#86]
@paul-gilbertson part of the staging geoserver seem to be having problems, specifically the ["Layers" menu](https://staging.ows.emodnet-seabedhabitats.eu/web/wicket/bookmarkable/org.geoserver.web.data.layer.LayerPage) - end up getting a service unavailable response (see below). 

![image](https://user-images.githubusercontent.com/30415162/60446168-b4530a80-9c18-11e9-9a08-033cdef7cfba.png)

Are you to check what's going on with this please?

**Comment by JordanPinder** [comment]
@paul-gilbertson have you had chance to look into this? Maybe a quick reboot might help?

**Comment by mattdebont** [comment]
Issue should now be resolved
