### ISSUE TITLE
Mapper & GDPR

### ISSUE THREAD

**Issue by JordanPinder** [jncc/web-mapper-core#89]
@JamesPe @SimonAnnetts @andyb-esdm  hi guys,  we've had some questions from the EMODnet Secretariat and Commission regarding GDPR compliance of the website. One specific thing we have been asked is:

"_Is the website setting consent requiring cookies when the browser’s “Do Not Track” (DNT) option is activated?_"

The cookies are already in use when the user arrives at the homepage. Just checking whether you know if any DNT options were put in place on the mapper application (https://mapper.emodnet-seabedhabitats.eu/)?

**Comment by andyb-esdm** [comment]
Hi Jordan,
I hope I understand you correctly.

The short answer to the question:
"Is the website setting consent requiring cookies when the browser’s “Do Not Track” (DNT) option is activated?"
Is no.

But there are no cookies or tracking from the mapper. It has no concept of a user's identity and stores nothing on the user's machine as a cookie or in local storage etc. By definition it doesn't track. It's a 'static' html file with JavaScript and only communicates with the api and geoserver to request information. Even restoring the map to a certain state is done through a url (permalink).

Of course, if the map is displayed via an iframe, then the hosting website may be setting cookies and will need to be GDPR compliant,.

Let me know if there's something we need to do about this but I am unsure if it applies to the mapper or how we could comply.

**Comment by andyb-esdm** [comment]
Hmm. On re-reading this I think 'no' is the right answer!

**Comment by JordanPinder** [comment]
@andyb-esdm thanks Andy! I had a feeling that was the case but just wanted to double check :) hosting site has cookies although that's something we're handling on our end.
