### ISSUE TITLE
GeoServer WFS - bad request Error 400

### ISSUE THREAD

**Issue by JordanPinder** [jncc/web-mapper-core#92]
Afternoon @JamesPe ! 

We had some queries about the GeoServer WFS returning:

An Error 400 for some layers; 

_"Layer OSPAR threatened and/or declining habitats - Polygons: Download of features for layer emodnet_open:ospar2018_poly failed or partially failed: Error when parsing GetFeature response : Error: XML or text declaration not at start of entity on line 1, column 471090. You may attempt reloading the layer with F5"_

Returning some layers which acting up;

![image](https://user-images.githubusercontent.com/30415162/64863481-d4e20c80-d62c-11e9-91d2-e9ae46e915d1.png)

And returning other layers as expected.

These have previously been working fine and no updates have been made so I'm a bit stumped as to what is causing the issue. Don't suppose you seen anything similar to this?

**Comment by JamesPe** [comment]
Hi @JordanPinder ,

I guess that's not in our mapper as we don't use WFS ?

Not seen that one before but I would guess you have an attribute for an object which is messing up the XML.  Suggestions that leading blank spaces can upset it?

When you say the layer was working before are you sure it was working for the same area - as I can imagine this error would only be hit when you were trying to get the WFS for objects in one particular area?

Other possibilities might be the return getting truncated in some way - is that a QGIS client in your screenshots ?

I've asked internally too - just in case anyone else has seen it

**Comment by GMDuncan** [comment]
In regards to the XML error, I've just tried downloading the ospar_polygons layer as GML through the Geoserver layer preview page, and at the bottom of the XML (once I upped the max features) was this:

`<ServiceExceptionReport
   version="1.2.0"
   xmlns="http://www.opengis.net/ogc"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wfs/1.0.0/OGC-exception.xsd">
   <ServiceException>
      java.lang.OutOfMemoryError: Java heap space
Java heap space
</ServiceException></ServiceExceptionReport>`

Which may well be the XML declaration in the error message in Jordan's post?

The stretchy polygons (on ospar_overview) seem to be separate to the XML error though, that GML loaded fine?
