### ISSUE TITLE
Mapper layer search

### ISSUE THREAD

**Issue by JordanPinder** [jncc/web-mapper-core#95]
Hi guys,

Just wanted to check the possibility of getting a (hopefully) minor addition to the mappers. 

We'd be interested in adding a "Layer search" option to allow users the ability to search for all layers within each mapper, click a matching result and turn that layer on. 

I imagine it would have similar functionality to the gazetteer with text matching, although such functionality might only be useful depending on the search terms individual put in. 

Do you think this would be feasible?

**Comment by andyb-esdm** [comment]
Hi @JordanPinder 
Yes. We could use the same type of control as the gazetteer but set its data source to the list of layers in the configuration, then make the layer active on click. I guess that might look right above the layer hierarchy in the left panel.
I don't think that would take more than a few hours but I will estimate it properly when I next look at the code. That will be this week when we continue with feature highlighting.

**Comment by JordanPinder** [comment]
Yup pretty much what we had in mind :) let me know what you come across.

**Comment by JordanPinder** [comment]
Hi @andyb-esdm, seems this dropped off my radar! Just wondering if you managed to look into this?

**Comment by andyb-esdm** [comment]
@JordanPinder started work on this now.

**Comment by andyb-esdm** [comment]
@JordanPinder This is implemented now and I've deployed to https://jnccdev-map.esdm.co.uk/ for testing.
There is a search box at the top of the left hand layers panel. It autocompletes on layer name. It will zoom you to the layer extent when you select a layer.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm seems to be working for me - zooms to the correct layer and turns it on. Does the search box use information from the layers api table?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Hi - yes. After the layers are loaded from the API configuration, it populates the dropdown with them. So it's different for each map instance. Searching is by the name field.

**Comment by JordanPinder** [comment]
Looks great, thanks @andyb-esdm. I'm happy for it to go to production, are you @HelenwoodsJNCC ?

**Comment by HelenwoodsJNCC** [comment]
@JordanPinder @andyb-esdm - Yes I am happy for it to go to production too. Thanks Andy!

**Comment by andyb-esdm** [comment]
Okay. Thanks.
